// ============================================================
// SEQUÊNCIA DIDÁTICA — Redes de Computadores — 3ª Série
// 40 semanas · 3h/semana · Carga Horária Total: 120h
// Técnico em Informática para Internet — SEDUC-PI
// PPC 2024 — IN SUPEN Nº 4/2024
// ============================================================

const AULAS = [
  // ─── 1º TRIMESTRE — UNIDADE I: Fundamentos de Redes ──────
  {
    sem: 1, tri: 1,
    tema: 'Apresentação da Disciplina e Diagnóstico Inicial',
    tipo: 'teoria',
    comp: 'Conhecer o plano da disciplina e mapear conhecimentos prévios sobre redes',
    hab: 'Identificar componentes de rede do cotidiano e formular perguntas sobre a disciplina',
    aval: 'Questionário diagnóstico e observação da participação (sem nota — mapeamento)',
    rec: 'Quadro e marcadores coloridos, questionário diagnóstico impresso, imagens de redes, caderno',
    quadro: [
      'REDES — SEM 01: APRESENTAÇÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'O que é uma rede de computadores?',
      '  "Dois ou mais dispositivos trocando dados"',
      ' ',
      'Sondagem: você já configurou uma rede?',
      '  Wi-Fi em casa | Cabo na escola',
      '  Impressora na rede | VPN',
      ' ',
      'Plano da disciplina — ementa PPC 2024',
      'Diário de Bordo: o que quero aprender'
    ],
    guia: null, tempos: []
  },
  {
    sem: 2, tri: 1,
    tema: 'História das Redes: da ARPANET à Internet Atual',
    tipo: 'teoria',
    comp: 'Compreender a evolução histórica das redes de computadores e o surgimento da Internet',
    hab: 'Construir linha do tempo das redes com marcos históricos e contexto tecnológico',
    aval: 'Linha do tempo em duplas e participação no debate (formativa)',
    rec: 'Slides com linha do tempo, vídeo sobre história da Internet (YouTube), projetor, caderno',
    quadro: [
      'REDES — SEM 02: HISTÓRIA DAS REDES',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'LINHA DO TEMPO:',
      '  1969 → ARPANET (4 computadores)',
      '  1974 → Protocolo TCP/IP (Cerf & Kahn)',
      '  1983 → Internet (TCP/IP adotado)',
      '  1991 → WWW (Tim Berners-Lee)',
      '  1993 → Mosaic (primeiro navegador)',
      '  2023 → 5 bilhões de usuários',
      ' ',
      'Atividade: linha do tempo em duplas'
    ],
    guia: null, tempos: []
  },
  {
    sem: 3, tri: 1,
    tema: 'Componentes Físicos de uma Rede',
    tipo: 'teoria',
    comp: 'Identificar e descrever os principais dispositivos e meios físicos de uma rede de computadores',
    hab: 'Reconhecer funções de hub, switch, roteador, placa de rede, modem e access point',
    aval: 'Jogo de identificação de componentes em grupos (formativa)',
    rec: 'Dispositivos reais ou imagens impressas, quadro, slides com funções e imagens',
    quadro: [
      'REDES — SEM 03: COMPONENTES FÍSICOS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'DISPOSITIVOS DE REDE:',
      '  Placa de rede (NIC) → interface do host',
      '  Hub → repete para TODAS as portas',
      '  Switch → encaminha ao destino certo',
      '  Roteador → conecta redes diferentes',
      '  Modem → modula/demodula o sinal',
      '  Access Point → rede sem fio',
      ' ',
      'MEIOS: cabo UTP | coaxial | fibra | Wi-Fi'
    ],
    guia: null, tempos: []
  },
  {
    sem: 4, tri: 1,
    tema: 'Topologias de Rede: Estrela, Barramento, Anel e Malha',
    tipo: 'teoria',
    comp: 'Compreender as diferentes topologias físicas e lógicas de rede e suas vantagens e desvantagens',
    hab: 'Desenhar e comparar topologias de rede identificando pontos de falha e escalabilidade',
    aval: 'Diagrama de topologia com análise de vantagens/desvantagens (formativa)',
    rec: 'Papel A3 ou cartolina, canetas coloridas, slides com diagramas, régua',
    quadro: [
      'REDES — SEM 04: TOPOLOGIAS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'ESTRELA: todos ligados a um switch central',
      '  + Falha em 1 nó não derruba a rede',
      '  - Depende do switch central',
      ' ',
      'BARRAMENTO: cabo coaxial compartilhado',
      'ANEL: token passado de nó em nó',
      'MALHA: cada nó ligado a todos os outros',
      '  + Redundância total | - Custo alto',
      ' ',
      'Atividade: desenhar topologia da escola'
    ],
    guia: null, tempos: []
  },
  {
    sem: 5, tri: 1,
    tema: 'Arquitetura Cliente-Servidor e Peer-to-Peer',
    tipo: 'teoria',
    comp: 'Compreender os modelos de comunicação cliente-servidor e P2P e suas aplicações reais',
    hab: 'Diferenciar os modelos e identificar exemplos em sistemas do cotidiano',
    aval: 'Análise de cenários e identificação do modelo adequado (formativa)',
    rec: 'Slides com diagramas de arquitetura, exemplos reais (Apache, torrente), quadro',
    quadro: [
      'REDES — SEM 05: ARQUITETURAS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CLIENTE-SERVIDOR:',
      '  Servidor: oferece serviços (HTTP, FTP)',
      '  Cliente: solicita e consome serviços',
      '  Ex: navegador ↔ servidor web',
      ' ',
      'PEER-TO-PEER (P2P):',
      '  Todos são clientes E servidores',
      '  Ex: BitTorrent | WhatsApp (mensagens)',
      ' ',
      'Cenários: qual arquitetura usar?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 6, tri: 1,
    tema: 'Meios de Transmissão Cabeados: Par Trançado, Coaxial e Fibra Óptica',
    tipo: 'teoria',
    comp: 'Identificar e comparar os meios de transmissão cabeados quanto a velocidade, custo e aplicação',
    hab: 'Reconhecer categorias de cabos UTP, características do coaxial e vantagens da fibra óptica',
    aval: 'Tabela comparativa dos meios de transmissão preenchida em duplas (formativa)',
    rec: 'Amostras reais ou fotos de cabos (Cat5e, Cat6, coaxial, fibra), slides, régua, caderno',
    quadro: [
      'REDES — SEM 06: MEIOS CABEADOS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PAR TRANÇADO:',
      '  UTP Cat5e → até 1 Gbps / 100m',
      '  UTP Cat6  → até 10 Gbps / 55m',
      '  Cat6A/Cat7 → datacenters',
      ' ',
      'COAXIAL: TV a cabo, Internet por cabo',
      ' ',
      'FIBRA ÓPTICA:',
      '  Monomodo → longas distâncias (km)',
      '  Multimodo → backbones locais'
    ],
    guia: null, tempos: []
  },
  {
    sem: 7, tri: 1,
    tema: 'Meios de Transmissão Sem Fio: Wi-Fi, Bluetooth e Redes Móveis',
    tipo: 'teoria',
    comp: 'Identificar tecnologias de transmissão sem fio e suas características técnicas e aplicações',
    hab: 'Comparar padrões IEEE 802.11 e classificar tecnologias sem fio por alcance e velocidade',
    aval: 'Mapa comparativo de tecnologias sem fio em grupos (formativa)',
    rec: 'Slides com tabela de padrões Wi-Fi, celulares para teste de Wi-Fi, roteador da escola',
    quadro: [
      'REDES — SEM 07: MEIOS SEM FIO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'WI-FI (IEEE 802.11):',
      '  802.11n  → até 600 Mbps (2.4/5 GHz)',
      '  802.11ac → até 3,5 Gbps (5 GHz)',
      '  802.11ax (Wi-Fi 6) → até 9,6 Gbps',
      ' ',
      'BLUETOOTH: até 10m | PAN',
      'INFRAVERMELHO: linha de visão | legado',
      '4G/5G: rede celular',
      ' ',
      'Teste: analisador de Wi-Fi no celular'
    ],
    guia: null, tempos: []
  },
  {
    sem: 8, tri: 1,
    tema: 'Modelo OSI — Camadas Superiores (Aplicação, Apresentação, Sessão)',
    tipo: 'teoria',
    comp: 'Compreender o Modelo OSI e as funções das camadas superiores na comunicação em rede',
    hab: 'Explicar o papel de cada camada superior e relacionar protocolos a camadas específicas',
    aval: 'Quiz de identificação de camadas e protocolos (formativa)',
    rec: 'Slides com diagrama OSI colorido, cartões de camadas para dinâmica, quadro',
    quadro: [
      'REDES — SEM 08: MODELO OSI I',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Modelo OSI — 7 Camadas (Open Systems)',
      ' ',
      '7. APLICAÇÃO   → HTTP, FTP, DNS, SMTP',
      '6. APRESENTAÇÃO → SSL/TLS, JPEG, ASCII',
      '5. SESSÃO      → NetBIOS, RPC',
      ' ',
      '"Encapsulamento": dados descem as camadas',
      '  adicionando cabeçalhos em cada etapa',
      ' ',
      'Mnemônico: "Antes Pratico Saber Todos",',
      '  "Redes Existem Fisicamente"'
    ],
    guia: null, tempos: []
  },
  {
    sem: 9, tri: 1,
    tema: 'Modelo OSI — Camadas Inferiores (Transporte, Rede, Enlace, Física)',
    tipo: 'teoria',
    comp: 'Compreender as funções das camadas inferiores do Modelo OSI e o papel dos protocolos',
    hab: 'Relacionar TCP e UDP à camada Transporte, IP à camada Rede e Ethernet à camada Enlace',
    aval: 'Exercício de encapsulamento simulado em papel (formativa)',
    rec: 'Slides com diagrama OSI completo, folhas para simulação de encapsulamento, quadro',
    quadro: [
      'REDES — SEM 09: MODELO OSI II',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '4. TRANSPORTE → TCP (confiável) / UDP',
      '3. REDE       → IP, ICMP, ARP',
      '2. ENLACE     → Ethernet, Wi-Fi (802.11)',
      '1. FÍSICA     → cabos, voltagens, sinais',
      ' ',
      'PDUs por camada:',
      '  Aplicação → Dados',
      '  Transporte → Segmento',
      '  Rede → Pacote',
      '  Enlace → Quadro',
      '  Física → Bits'
    ],
    guia: null, tempos: []
  },
  {
    sem: 10, tri: 1,
    tema: 'Suite TCP/IP — Comparação com o Modelo OSI e Revisão',
    tipo: 'aval',
    comp: 'Consolidar os conceitos da Unidade I comparando os modelos OSI e TCP/IP',
    hab: 'Mapear protocolos nos modelos OSI e TCP/IP e resolver exercícios de revisão',
    aval: 'Quiz e ficha de autoavaliação (diagnóstico formativo)',
    rec: 'Kahoot (celular) ou perguntas impressas, slides comparativos OSI vs TCP/IP, quadro',
    quadro: [
      'REDES — SEM 10: TCP/IP E REVISÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'MODELO TCP/IP (4 camadas):',
      '  Aplicação  → HTTP, FTP, DNS, SMTP',
      '  Transporte → TCP, UDP',
      '  Internet   → IP, ICMP',
      '  Ac. à Rede → Ethernet, Wi-Fi',
      ' ',
      'OSI ↔ TCP/IP:',
      '  7+6+5 → Aplicação',
      '  4 → Transporte | 3 → Internet',
      '  2+1 → Acesso à Rede'
    ],
    guia: null, tempos: []
  },
  {
    sem: 11, tri: 1,
    tema: 'AQL — 1º Trimestre (Avaliação Qualitativa)',
    tipo: 'aval',
    comp: 'Demonstrar compreensão dos fundamentos de redes, meios de transmissão e modelos OSI/TCP',
    hab: 'Produzir texto técnico, apresentar oralmente e participar de atividade avaliativa',
    aval: 'AQL: Produção Textual 40% + Oralidade 30% + Participação 30% — IN SUPEN Nº 4/2024',
    rec: 'Ficha de avaliação AQL, caderno, rubrica de produção textual e oralidade',
    quadro: [
      'REDES — AQL 1º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQL — Avaliação Qualitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Produção Textual (40%):',
      '  Resumo técnico sobre Modelo OSI',
      ' ',
      'Oralidade (30%):',
      '  Apresentação 2-3 min: topologia de rede',
      ' ',
      'Participação (30%):',
      '  Engajamento nas atividades do trimestre'
    ],
    guia: null, tempos: []
  },
  {
    sem: 12, tri: 1,
    tema: 'AQT — 1º Trimestre (Avaliação Quantitativa)',
    tipo: 'aval',
    comp: 'Demonstrar domínio conceitual dos conteúdos do 1º Trimestre por avaliação escrita',
    hab: 'Responder questões objetivas e discursivas sobre fundamentos, topologias, meios e modelos OSI/TCP',
    aval: 'AQT: 50% múltipla escolha + 50% discursiva — IN SUPEN Nº 4/2024',
    rec: 'Prova impressa, caneta, folha de respostas',
    quadro: [
      'REDES — AQT 1º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQT — Avaliação Quantitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Múltipla Escolha (50%):',
      '  10 questões sobre Unidade I',
      ' ',
      'Discursiva (50%):',
      '  2 questões de aplicação prática',
      ' ',
      'Temas: topologias, meios, OSI, TCP/IP',
      '  componentes físicos, arquiteturas'
    ],
    guia: null, tempos: []
  },
  {
    sem: 13, tri: 1,
    tema: 'RPT — Recuperação Parcial 1º Trimestre',
    tipo: 'aval',
    comp: 'Recuperar e consolidar os conteúdos do 1º Trimestre com foco nas dificuldades identificadas',
    hab: 'Demonstrar compreensão dos conceitos com defasagem identificada nas avaliações anteriores',
    aval: 'RPT: Revisão dirigida + atividade de recuperação (IN SUPEN Nº 4/2024)',
    rec: 'Exercícios de revisão impressos, quadro, fichas por conteúdo com dificuldade',
    quadro: [
      'REDES — RPT 1º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'RECUPERAÇÃO PARCIAL',
      ' ',
      'Revisão por dificuldade identificada:',
      '  Topologias e componentes',
      '  Modelo OSI: camadas e PDUs',
      '  TCP/IP: camadas e protocolos',
      '  Meios de transmissão',
      ' ',
      'Atividade de recuperação:',
      '  Questões dirigidas por dificuldade'
    ],
    guia: null, tempos: []
  },

  // ─── 2º TRIMESTRE — UNIDADE II: Redes e Endereçamento IP ──
  {
    sem: 14, tri: 2,
    tema: 'LAN — Rede de Área Local: Características e Dispositivos',
    tipo: 'teoria',
    comp: 'Compreender as características técnicas de redes LAN e identificar dispositivos e padrões',
    hab: 'Identificar padrões Ethernet, dispositivos de interconexão e topologias comuns em LAN',
    aval: 'Diagrama de LAN escolar com dispositivos e cabeamento (formativa)',
    rec: 'Slides com topologia LAN, imagens de switchs gerenciáveis, papel para diagrama',
    quadro: [
      'REDES — SEM 14: LAN',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'LAN — Local Area Network',
      '  Alcance: um prédio ou campus',
      '  Velocidade: 100 Mbps a 10 Gbps',
      '  Tecnologia: Ethernet (IEEE 802.3)',
      ' ',
      'DISPOSITIVOS TÍPICOS:',
      '  Switches | Roteadores | APs',
      '  Patch panels | Cabeamento estruturado',
      ' ',
      'Atividade: diagrama da LAN da escola'
    ],
    guia: null, tempos: []
  },
  {
    sem: 15, tri: 2,
    tema: 'Prática: Montagem de Cabo de Rede e Conector RJ-45',
    tipo: 'pratica',
    comp: 'Aplicar os padrões TIA-568A e TIA-568B na confecção de cabos de rede UTP',
    hab: 'Montar cabo direto e cabo crossover com conector RJ-45 e testar conectividade',
    aval: 'Cabo de rede montado e testado com sucesso (avaliação prática)',
    rec: 'Cabo UTP Cat5e/Cat6, conectores RJ-45, alicate crimper, testador de cabo por aluno/dupla',
    quadro: [
      'REDES — SEM 15: CABO RJ-45',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PADRÃO T568B (mais comum no Brasil):',
      '  1. Branco-laranja  2. Laranja',
      '  3. Branco-verde    4. Azul',
      '  5. Branco-azul     6. Verde',
      '  7. Branco-marrom   8. Marrom',
      ' ',
      'DIRETO: PC ↔ Switch (mesmo padrão)',
      'CROSS:  PC ↔ PC (padrões opostos)',
      ' ',
      'Etapas: medir | decapar | ordenar | crimpar | testar'
    ],
    guia: null, tempos: []
  },
  {
    sem: 16, tri: 2,
    tema: 'MAN e WAN — Redes Metropolitanas e de Longa Distância',
    tipo: 'teoria',
    comp: 'Compreender as características de redes MAN e WAN e sua infraestrutura de conectividade',
    hab: 'Comparar LAN, MAN e WAN quanto a alcance, tecnologia e velocidade',
    aval: 'Tabela comparativa LAN/MAN/WAN com exemplos reais (formativa)',
    rec: 'Slides com mapa de fibra óptica do Brasil, vídeo sobre cabo submarino, quadro',
    quadro: [
      'REDES — SEM 16: MAN E WAN',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'MAN — Metropolitan Area Network',
      '  Alcance: cidade ou região',
      '  Ex: rede da prefeitura, fibra municipal',
      ' ',
      'WAN — Wide Area Network',
      '  Alcance: países e continentes',
      '  Tecnologias: fibra submarina, satélite',
      '  Ex: Internet, redes corporativas globais',
      ' ',
      'LAN < MAN < WAN (escala de abrangência)'
    ],
    guia: null, tempos: []
  },
  {
    sem: 17, tri: 2,
    tema: 'Protocolo IPv4 — Estrutura do Endereço e Classes',
    tipo: 'teoria',
    comp: 'Compreender a estrutura do endereço IPv4 e identificar as classes de endereços',
    hab: 'Converter endereços IP para binário e identificar classes A, B, C, D e E',
    aval: 'Lista de exercícios de conversão e identificação de classes (formativa)',
    rec: 'Slides com notação decimal pontilhada, tabela de classes, calculadora ou papel',
    quadro: [
      'REDES — SEM 17: IPV4 E CLASSES',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IPv4: 32 bits = 4 octetos',
      '  Ex: 192.168.1.1',
      '  Bin: 11000000.10101000.00000001.00000001',
      ' ',
      'CLASSES:',
      '  A: 0–127   | /8  | redes grandes',
      '  B: 128–191 | /16 | médias',
      '  C: 192–223 | /24 | pequenas',
      '  D: 224–239 | Multicast',
      '  E: 240–255 | Reservado/Experimental'
    ],
    guia: null, tempos: []
  },
  {
    sem: 18, tri: 2,
    tema: 'Máscara de Sub-rede, Gateway Padrão e Endereços Reservados',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento de máscara de sub-rede e identificar endereços IP reservados',
    hab: 'Determinar rede, broadcast e hosts válidos a partir de um endereço IP e máscara',
    aval: 'Exercícios de cálculo de rede e broadcast com máscaras /24, /16 e /8 (formativa)',
    rec: 'Slides com exemplos de cálculo, lista de exercícios impressa, quadro para resolução',
    quadro: [
      'REDES — SEM 18: MÁSCARA E GATEWAY',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'MÁSCARA /24: 255.255.255.0',
      '  IP:    192.168.1.45',
      '  Rede:  192.168.1.0',
      '  Bcast: 192.168.1.255',
      '  Hosts: 192.168.1.1–254 (254 hosts)',
      ' ',
      'GATEWAY: roteador padrão da rede',
      ' ',
      'ENDEREÇOS RESERVADOS (RFC 1918):',
      '  10.x.x.x | 172.16–31.x.x | 192.168.x.x',
      '  127.0.0.1 = loopback'
    ],
    guia: null, tempos: []
  },
  {
    sem: 19, tri: 2,
    tema: 'Sub-redes: Conceito CIDR e Divisão de Redes',
    tipo: 'teoria',
    comp: 'Compreender a notação CIDR e realizar divisão básica de sub-redes',
    hab: 'Calcular sub-redes com CIDR e determinar blocos de endereços disponíveis',
    aval: 'Exercício de sub-redes em laboratório (formativa)',
    rec: 'Folhas de exercícios de sub-redes, calculadora, slides com exemplos passo a passo',
    quadro: [
      'REDES — SEM 19: SUB-REDES E CIDR',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CIDR: Classless Inter-Domain Routing',
      '  192.168.1.0/26',
      '  → 26 bits para rede, 6 para hosts',
      '  → 2⁶ - 2 = 62 hosts úteis',
      ' ',
      'Dividindo /24 em 4 sub-redes (/26):',
      '  .0/26  | .64/26',
      '  .128/26 | .192/26',
      ' ',
      'Fórmula: 2ⁿ sub-redes, 2ʰ - 2 hosts'
    ],
    guia: null, tempos: []
  },
  {
    sem: 20, tri: 2,
    tema: 'Prática: Configuração de Endereçamento IP em Windows e Linux',
    tipo: 'pratica',
    comp: 'Configurar endereçamento IP manualmente em sistemas Windows e Linux',
    hab: 'Definir IP, máscara, gateway e DNS manualmente e verificar conectividade',
    aval: 'Relatório de configuração de rede com captura de tela (avaliação prática)',
    rec: 'Laboratório com computadores Windows e Linux (ou VMs), acesso de administrador',
    quadro: [
      'REDES — SEM 20: CONFIG. IP NA PRÁTICA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'WINDOWS:',
      '  Painel → Rede → Adaptador',
      '  TCP/IPv4 → IP / Máscara / GW / DNS',
      '  Verificar: ipconfig /all',
      ' ',
      'LINUX:',
      '  ip addr show',
      '  ip addr add 192.168.1.10/24 dev eth0',
      '  ip route add default via 192.168.1.1',
      ' ',
      'Testar: ping 192.168.1.1 | ping 8.8.8.8'
    ],
    guia: null, tempos: []
  },
  {
    sem: 21, tri: 2,
    tema: 'Protocolo TCP — Orientado a Conexão e Three-Way Handshake',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento do protocolo TCP e o processo de estabelecimento de conexão',
    hab: 'Explicar o Three-Way Handshake e identificar campos do cabeçalho TCP',
    aval: 'Simulação do Three-Way Handshake em papel e participação (formativa)',
    rec: 'Slides com diagrama do handshake, demo Wireshark (opcional), folhas para simulação',
    quadro: [
      'REDES — SEM 21: PROTOCOLO TCP',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'TCP — Transmission Control Protocol',
      '  Orientado à conexão | Confiável',
      '  Controle de fluxo | Ordenação',
      ' ',
      'THREE-WAY HANDSHAKE:',
      '  1. Cliente → SYN   → Servidor',
      '  2. Servidor → SYN-ACK → Cliente',
      '  3. Cliente → ACK   → Servidor',
      '  → Conexão estabelecida!',
      ' ',
      'Uso: HTTP, HTTPS, FTP, SMTP, SSH'
    ],
    guia: null, tempos: []
  },
  {
    sem: 22, tri: 2,
    tema: 'Protocolo UDP — Sem Conexão e Aplicações em Tempo Real',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento do UDP e identificar cenários onde é preferível ao TCP',
    hab: 'Comparar TCP e UDP quanto a confiabilidade, latência e uso em aplicações reais',
    aval: 'Quadro comparativo TCP × UDP com exemplos de uso (formativa)',
    rec: 'Slides com diagrama UDP, exemplos de streaming, vídeo de diferença TCP vs UDP',
    quadro: [
      'REDES — SEM 22: PROTOCOLO UDP',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'UDP — User Datagram Protocol',
      '  Sem conexão | Sem garantia de entrega',
      '  Rápido | Baixa latência',
      ' ',
      'CABEÇALHO: só 4 campos (8 bytes)',
      '  Porta origem | Porta destino',
      '  Tamanho | Checksum',
      ' ',
      'QUANDO USAR UDP:',
      '  Streaming de vídeo/áudio | Games online',
      '  DNS | DHCP | VoIP | IPTV',
      ' ',
      'TCP: confiável | UDP: rápido'
    ],
    guia: null, tempos: []
  },
  {
    sem: 23, tri: 2,
    tema: 'Portas de Rede e Serviços Comuns',
    tipo: 'teoria',
    comp: 'Identificar as principais portas de rede e relacioná-las aos serviços correspondentes',
    hab: 'Associar números de porta a protocolos e usar ferramentas de diagnóstico de portas',
    aval: 'Lista de portas associadas a serviços + exercício de análise de conexão ativa (formativa)',
    rec: 'Slides com tabela de portas, netstat no laboratório, quadro',
    quadro: [
      'REDES — SEM 23: PORTAS E SERVIÇOS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PORTAS WELL-KNOWN (0–1023):',
      '  20/21 FTP | 22 SSH | 23 Telnet',
      '  25 SMTP | 53 DNS | 67/68 DHCP',
      '  80 HTTP | 110 POP3 | 143 IMAP',
      '  443 HTTPS | 3389 RDP',
      ' ',
      'Verificar conexões ativas:',
      '  netstat -an (Windows/Linux)',
      ' ',
      'Socket = IP + Porta',
      '  192.168.1.1:443'
    ],
    guia: null, tempos: []
  },
  {
    sem: 24, tri: 2,
    tema: 'Revisão da Unidade II — Exercícios de Endereçamento e Protocolos',
    tipo: 'aval',
    comp: 'Revisar e consolidar LAN/MAN/WAN, IPv4, sub-redes e protocolos TCP/UDP',
    hab: 'Resolver exercícios de endereçamento IP e identificar protocolos e portas',
    aval: 'Quiz de revisão com exercícios práticos de cálculo de sub-rede (diagnóstico formativo)',
    rec: 'Lista de exercícios de revisão impressa, calculadora, quadro',
    quadro: [
      'REDES — SEM 24: REVISÃO UNIDADE II',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'REVISÃO:',
      '  LAN | MAN | WAN',
      '  Classes IPv4 | CIDR | Máscaras',
      '  Sub-redes | Hosts válidos',
      '  TCP × UDP | Portas e serviços',
      ' ',
      'Exercício resolvido:',
      '  192.168.10.0/25',
      '  → Rede | Broadcast | Hosts | Sub-redes',
      ' ',
      'Quiz de consolidação — 20 questões'
    ],
    guia: null, tempos: []
  },
  {
    sem: 25, tri: 2,
    tema: 'AQL — 2º Trimestre (Avaliação Qualitativa)',
    tipo: 'aval',
    comp: 'Demonstrar compreensão de LAN/MAN/WAN, endereçamento IPv4, TCP/UDP e portas',
    hab: 'Produzir texto técnico sobre sub-redes e apresentar configuração de rede oralmente',
    aval: 'AQL: Produção Textual 40% + Oralidade 30% + Participação 30% — IN SUPEN Nº 4/2024',
    rec: 'Ficha de avaliação AQL, rubrica de produção textual e oralidade, caderno',
    quadro: [
      'REDES — AQL 2º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQL — Avaliação Qualitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Produção Textual (40%):',
      '  Relatório de configuração de rede',
      ' ',
      'Oralidade (30%):',
      '  Apresentação: projeto de endereçamento',
      ' ',
      'Participação (30%):',
      '  Engajamento nas práticas do trimestre'
    ],
    guia: null, tempos: []
  },
  {
    sem: 26, tri: 2,
    tema: 'AQT — 2º Trimestre (Avaliação Quantitativa)',
    tipo: 'aval',
    comp: 'Demonstrar domínio dos conteúdos do 2º Trimestre por avaliação escrita',
    hab: 'Resolver questões objetivas e discursivas sobre LAN/MAN/WAN, IPv4, TCP/UDP',
    aval: 'AQT: 50% múltipla escolha + 50% discursiva — IN SUPEN Nº 4/2024',
    rec: 'Prova impressa, caneta, calculadora',
    quadro: [
      'REDES — AQT 2º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQT — Avaliação Quantitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Múltipla Escolha (50%):',
      '  10 questões — Unidade II',
      ' ',
      'Discursiva (50%):',
      '  Cálculo de sub-redes + análise de protocolo',
      ' ',
      'Temas: LAN/MAN/WAN | IPv4 | Sub-redes',
      '  TCP × UDP | Portas | Config. IP'
    ],
    guia: null, tempos: []
  },
  {
    sem: 27, tri: 2,
    tema: 'RPT — Recuperação Parcial 2º Trimestre',
    tipo: 'aval',
    comp: 'Recuperar e consolidar os conteúdos do 2º Trimestre com foco nas dificuldades identificadas',
    hab: 'Demonstrar compreensão dos conceitos com defasagem, especialmente endereçamento IP',
    aval: 'RPT: Revisão dirigida + atividade de recuperação (IN SUPEN Nº 4/2024)',
    rec: 'Exercícios de revisão impressos, quadro, fichas por conteúdo',
    quadro: [
      'REDES — RPT 2º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'RECUPERAÇÃO PARCIAL',
      ' ',
      'Revisão por dificuldade:',
      '  LAN/MAN/WAN e topologias',
      '  Classes IPv4 e conversão binária',
      '  Cálculo de sub-redes CIDR',
      '  TCP × UDP e portas',
      ' ',
      'Atividade de recuperação:',
      '  Exercícios de endereçamento'
    ],
    guia: null, tempos: []
  },

  // ─── 3º TRIMESTRE — UNIDADE III: Serviços de Rede ─────────
  {
    sem: 28, tri: 3,
    tema: 'DNS — Sistema de Nomes de Domínio: Funcionamento e Hierarquia',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento do DNS e a hierarquia de domínios na Internet',
    hab: 'Explicar a resolução de nomes, identificar registros DNS e usar ferramentas de consulta',
    aval: 'Consultas DNS com nslookup/dig e interpretação dos resultados (formativa)',
    rec: 'Computadores com internet, slides com hierarquia DNS, terminal/cmd',
    quadro: [
      'REDES — SEM 28: DNS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'DNS — Domain Name System',
      '  Traduz: www.google.com → 142.250.x.x',
      ' ',
      'HIERARQUIA:',
      '  . (root) → .com → google.com → www',
      ' ',
      'REGISTROS DNS:',
      '  A → IPv4 | AAAA → IPv6',
      '  MX → email | CNAME → alias',
      '  NS → servidor de nome',
      ' ',
      'Prática: nslookup google.com | dig'
    ],
    guia: null, tempos: []
  },
  {
    sem: 29, tri: 3,
    tema: 'DHCP — Configuração Automática de Endereços IP',
    tipo: 'teoria',
    comp: 'Compreender o protocolo DHCP e o processo de concessão automática de endereços IP',
    hab: 'Explicar as etapas DORA e identificar configurações de escopo DHCP',
    aval: 'Simulação do processo DORA em papel e análise de configuração DHCP (formativa)',
    rec: 'Slides com diagrama DORA, servidor DHCP real ou VM para demonstração',
    quadro: [
      'REDES — SEM 29: DHCP',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'DHCP — Dynamic Host Configuration Protocol',
      '  Porta 67 (servidor) / 68 (cliente)',
      ' ',
      'PROCESSO DORA:',
      '  D → Discover (broadcast: "tem DHCP?")',
      '  O → Offer   (servidor: "tenho IP")',
      '  R → Request (cliente: "quero esse IP")',
      '  A → Ack     (servidor: "confirmado")',
      ' ',
      'ESCOPO: pool de IPs | lease | DNS | GW'
    ],
    guia: null, tempos: []
  },
  {
    sem: 30, tri: 3,
    tema: 'Proxy — Servidor Intermediário: Tipos e Configuração',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento de servidores proxy e sua aplicação em controle de acesso',
    hab: 'Diferenciar proxy direto, reverso e transparente e identificar casos de uso corporativos',
    aval: 'Análise de cenários de uso de proxy em organizações (formativa)',
    rec: 'Slides com diagrama de proxy, exemplos de logs de acesso, casos reais',
    quadro: [
      'REDES — SEM 30: PROXY',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PROXY: intermediário entre cliente e Internet',
      ' ',
      'TIPOS:',
      '  Proxy direto: controla saída dos clientes',
      '    → Filtragem de conteúdo | Logs',
      '  Proxy reverso: protege servidores',
      '    → Nginx | Load balancer | Cache',
      '  Transparente: sem config. no cliente',
      ' ',
      'BENEFÍCIOS: cache | filtro | anonimato',
      'FERRAMENTA: Squid (Linux)'
    ],
    guia: null, tempos: []
  },
  {
    sem: 31, tri: 3,
    tema: 'Firewall — Segurança de Redes: Tipos, Regras e Políticas',
    tipo: 'teoria',
    comp: 'Compreender o funcionamento de firewalls e criar políticas de segurança de rede',
    hab: 'Diferenciar firewall de pacotes, stateful e UTM e criar regras básicas de filtragem',
    aval: 'Criação de política de firewall para cenário de escola/empresa (formativa)',
    rec: 'Slides com tipos de firewall, exemplos de regras iptables, casos reais de ataque',
    quadro: [
      'REDES — SEM 31: FIREWALL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'FIREWALL: barreira entre rede interna e externa',
      ' ',
      'TIPOS:',
      '  Filtro de pacotes: analisa header IP/TCP',
      '  Stateful: rastreia estado das conexões',
      '  UTM: anti-vírus + IDS + VPN + filtro',
      ' ',
      'REGRAS BÁSICAS (iptables):',
      '  -A INPUT -p tcp --dport 22 -j ACCEPT',
      '  -A INPUT -j DROP',
      ' ',
      'Default Deny vs Default Allow'
    ],
    guia: null, tempos: []
  },
  {
    sem: 32, tri: 3,
    tema: 'NAT e Segurança em Redes: VPN e Criptografia Básica',
    tipo: 'teoria',
    comp: 'Compreender NAT e os fundamentos de VPN e criptografia aplicados à segurança de redes',
    hab: 'Explicar como o NAT traduz endereços e como uma VPN cifra e protege o tráfego',
    aval: 'Análise de cenários de segurança com NAT e VPN (formativa)',
    rec: 'Slides com diagrama NAT e VPN, vídeo sobre funcionamento de VPN, quadro',
    quadro: [
      'REDES — SEM 32: NAT E VPN',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'NAT — Network Address Translation',
      '  IP privado → IP público compartilhado',
      '  Mascara endereços internos da Internet',
      ' ',
      'VPN — Virtual Private Network',
      '  Túnel criptografado sobre a Internet',
      '  Protocolos: OpenVPN | WireGuard | IPSec',
      ' ',
      'CRIPTOGRAFIA BÁSICA:',
      '  Simétrica: AES | Assimétrica: RSA',
      '  TLS/HTTPS: protege dados em trânsito'
    ],
    guia: null, tempos: []
  },
  {
    sem: 33, tri: 3,
    tema: 'Prática: Configuração de DNS e DHCP em Laboratório',
    tipo: 'pratica',
    comp: 'Configurar serviços DNS e DHCP em ambiente de laboratório Linux/Windows Server',
    hab: 'Instalar e configurar servidor DHCP e criar zona DNS em ambiente local',
    aval: 'Relatório de configuração com captura de tela e teste de funcionamento (avaliação prática)',
    rec: 'VMs Linux (Ubuntu Server) ou Windows Server, acesso administrativo, roteiro de laboratório',
    quadro: [
      'REDES — SEM 33: LAB DNS E DHCP',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'DHCP no Linux (isc-dhcp-server):',
      '  subnet 192.168.1.0 netmask 255.255.255.0 {',
      '    range 192.168.1.100 192.168.1.200;',
      '    option routers 192.168.1.1;',
      '  }',
      ' ',
      'DNS no Linux (BIND9):',
      '  named.conf.local → zona local',
      '  db.escola.local  → registros A',
      ' ',
      'Testar: dig @localhost escola.local'
    ],
    guia: null, tempos: []
  },
  {
    sem: 34, tri: 3,
    tema: 'Diagnóstico de Problemas de Rede: Ferramentas e Metodologia',
    tipo: 'pratica',
    comp: 'Aplicar ferramentas de diagnóstico para identificar e solucionar problemas de rede',
    hab: 'Usar ping, traceroute, nslookup, netstat e ipconfig/ifconfig para diagnosticar falhas',
    aval: 'Resolução de cenários de falha de rede em laboratório (avaliação prática)',
    rec: 'Computadores em rede, acesso ao terminal, cenários de falha preparados pelo professor',
    quadro: [
      'REDES — SEM 34: DIAGNÓSTICO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'FERRAMENTAS:',
      '  ping 8.8.8.8       → testa conectividade',
      '  traceroute/tracert → rota até destino',
      '  nslookup           → consulta DNS',
      '  netstat -an        → conexões ativas',
      '  ipconfig /all (Win) | ip addr (Linux)',
      ' ',
      'METODOLOGIA OSI BOTTOM-UP:',
      '  1. Física → 2. Enlace → 3. Rede',
      '  → 4. Transporte → 5-7. Aplicação'
    ],
    guia: null, tempos: []
  },
  {
    sem: 35, tri: 3,
    tema: 'IPv6 e Lançamento do Projeto Final',
    tipo: 'teoria',
    comp: 'Conhecer o protocolo IPv6 e suas vantagens em relação ao IPv4, e planejar o projeto final',
    hab: 'Identificar a estrutura do endereço IPv6 e elaborar plano de projeto de rede',
    aval: 'Plano do Projeto Final entregue (pré-requisito) + quiz IPv6 (formativa)',
    rec: 'Slides com estrutura IPv6, roteiro e ficha de planejamento do projeto final',
    quadro: [
      'REDES — SEM 35: IPv6 + PROJETO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IPv6: 128 bits = 8 grupos de 16 bits',
      '  2001:0db8:85a3::8a2e:0370:7334',
      '  4,3 × 10³⁸ endereços!',
      ' ',
      'Por quê IPv6?',
      '  IPv4 esgotado em 2011 (IANA)',
      '  + Segurança nativa (IPSec)',
      '  + Autoconfiguração (SLAAC)',
      ' ',
      'PROJETO FINAL: projetar rede para escola',
      '  Topologia | Endereçamento | Serviços'
    ],
    guia: null, tempos: []
  },
  {
    sem: 36, tri: 3,
    tema: 'Desenvolvimento do Projeto Final — Parte I',
    tipo: 'projeto',
    comp: 'Desenvolver o projeto de rede aplicando os conhecimentos da disciplina',
    hab: 'Elaborar diagrama de topologia, esquema de endereçamento e lista de equipamentos',
    aval: 'Acompanhamento do projeto — progresso e metodologia (formativa)',
    rec: 'Computadores, Cisco Packet Tracer ou papel, roteiro do projeto, ficha de acompanhamento',
    quadro: [
      'REDES — SEM 36: PROJETO I',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PROJETO: Rede para escola/empresa',
      ' ',
      'ENTREGÁVEIS PARTE I:',
      '  Diagrama de topologia lógica',
      '  Esquema de endereçamento IP',
      '  Lista de equipamentos necessários',
      ' ',
      'Status Check:',
      '  O que fizemos | O que falta',
      '  Precisamos de ajuda com: ___'
    ],
    guia: null, tempos: []
  },
  {
    sem: 37, tri: 3,
    tema: 'Desenvolvimento do Projeto Final — Parte II',
    tipo: 'projeto',
    comp: 'Completar o projeto de rede com configuração de serviços e políticas de segurança',
    hab: 'Definir serviços DNS, DHCP, proxy e regras de firewall para o projeto de rede',
    aval: 'Produto quase finalizado com todos os serviços planejados (formativa)',
    rec: 'Computadores, Packet Tracer/GNS3 ou documentação escrita, roteiro de entrega',
    quadro: [
      'REDES — SEM 37: PROJETO II',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'ENTREGÁVEIS PARTE II:',
      '  Configuração de DNS e DHCP',
      '  Política de firewall (regras)',
      '  Configuração de proxy',
      '  Documentação técnica da rede',
      ' ',
      'Feedback de pares:',
      '  1 ponto forte | 1 sugestão',
      ' ',
      'Entrega final: próxima semana'
    ],
    guia: null, tempos: []
  },
  {
    sem: 38, tri: 3,
    tema: 'AQL — 3º Trimestre (Avaliação Qualitativa)',
    tipo: 'aval',
    comp: 'Demonstrar compreensão dos serviços DNS, DHCP, proxy, firewall e do projeto de rede',
    hab: 'Produzir relatório técnico e apresentar o projeto de rede oralmente',
    aval: 'AQL: Produção Textual 40% + Oralidade 30% + Participação 30% — IN SUPEN Nº 4/2024',
    rec: 'Ficha de avaliação AQL, rubrica de apresentação, caderno',
    quadro: [
      'REDES — AQL 3º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQL — Avaliação Qualitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Produção Textual (40%):',
      '  Relatório do projeto de rede',
      ' ',
      'Oralidade (30%):',
      '  Apresentação do projeto final (5 min)',
      ' ',
      'Participação (30%):',
      '  Engajamento nas atividades do trimestre'
    ],
    guia: null, tempos: []
  },
  {
    sem: 39, tri: 3,
    tema: 'AQT — 3º Trimestre (Avaliação Quantitativa)',
    tipo: 'aval',
    comp: 'Demonstrar domínio dos conteúdos do 3º Trimestre por avaliação escrita',
    hab: 'Resolver questões objetivas e discursivas sobre DNS, DHCP, proxy, firewall e IPv6',
    aval: 'AQT: 50% múltipla escolha + 50% discursiva — IN SUPEN Nº 4/2024',
    rec: 'Prova impressa, caneta, calculadora',
    quadro: [
      'REDES — AQT 3º TRIMESTRE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AQT — Avaliação Quantitativa',
      '  IN SUPEN Nº 4/2024',
      ' ',
      'Múltipla Escolha (50%):',
      '  10 questões — Unidade III',
      ' ',
      'Discursiva (50%):',
      '  Análise de topologia + serviços de rede',
      ' ',
      'Temas: DNS | DHCP | Proxy | Firewall',
      '  NAT | VPN | IPv6 | Diagnóstico'
    ],
    guia: null, tempos: []
  },
  {
    sem: 40, tri: 3,
    tema: 'RPT — Recuperação Final + Entrega e Apresentação do Projeto',
    tipo: 'aval',
    comp: 'Encerrar a disciplina com entrega do projeto final e recuperação dos conteúdos pendentes',
    hab: 'Apresentar projeto de rede completo e demonstrar domínio dos conteúdos da disciplina',
    aval: 'RPT + Entrega do Projeto Final + Autoavaliação (IN SUPEN Nº 4/2024)',
    rec: 'Projetor, ficha de autoavaliação final, checklist do projeto',
    quadro: [
      'REDES — RPT + ENCERRAMENTO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'RECUPERAÇÃO FINAL:',
      '  Alunos com nota < 6.0',
      '  Atividade recuperativa oral/escrita',
      ' ',
      'PROJETO FINAL:',
      '  Entrega da documentação completa',
      '  Apresentação (5 min por grupo)',
      ' ',
      'AUTOAVALIAÇÃO:',
      '  O que aprendi | Como aplico no mercado',
      '  Onde tenho mais dificuldade'
    ],
    guia: null, tempos: []
  }
];
