// ============================================================
// SEQUÊNCIA DIDÁTICA — Inteligência Artificial — 1º Ano EM
// 40 Aulas · 1 hora cada · Carga Horária Total: 40h
// Alinhado à BNCC — SEDUC-PI
// ============================================================

const AULAS = [
  // ─── 1º TRIMESTRE — UNIDADE I: O que é IA? ────────────────
  {
    sem: 1, tri: 1,
    tema: 'Apresentação da Disciplina e Sondagem Inicial',
    tipo: 'teoria',
    comp: 'Conhecer a disciplina e levantar conhecimentos prévios sobre IA',
    hab: 'Mapear concepções iniciais e criar ambiente de aprendizagem colaborativo',
    aval: 'Observação da participação e questionário diagnóstico (sem nota — mapeamento)',
    rec: 'Quadro e marcadores coloridos, questionário impresso ou Google Forms, imagens de IA, caderno do estudante (Diário de Bordo)',
    quadro: [
      'IA — AULA 01: APRESENTAÇÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Dinâmica: nome + tecnologia que usa',
      ' ',
      'Sondagem individual:',
      '  "O que você já sabe sobre IA?"',
      '  YouTube escolhe vídeos para você?',
      ' ',
      'Mapa mental coletivo no quadro',
      'Diário de Bordo: o que espero aprender'
    ],
    guia: null, tempos: []
  },
  {
    sem: 2, tri: 1,
    tema: 'O que é Inteligência Artificial? Conceito e História',
    tipo: 'teoria',
    comp: 'Compreender o conceito de IA e sua evolução histórica',
    hab: 'Construir linha do tempo da IA com marcos históricos contextualizados',
    aval: 'Linha do tempo em duplas — compreensão cronológica (formativa)',
    rec: 'Slides com linha do tempo, vídeo Kurzgesagt (YouTube), projetor, caderno do estudante',
    quadro: [
      'IA — AULA 02: CONCEITO E HISTÓRIA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'LINHA DO TEMPO:',
      '  1950 → Turing (Jogo da Imitação)',
      '  1956 → Conferência de Dartmouth',
      '  1997 → Deep Blue x Kasparov',
      '  2012 → Redes Neurais Profundas',
      '  2022 → ChatGPT',
      ' ',
      'Atividade: linha do tempo em duplas'
    ],
    guia: null, tempos: []
  },
  {
    sem: 3, tri: 1,
    tema: 'IA Fraca vs. IA Forte — Tipos e Exemplos',
    tipo: 'teoria',
    comp: 'Diferenciar IA Estreita de IA Geral e identificar exemplos no cotidiano',
    hab: 'Classificar sistemas de IA como fraca, forte ou ficção científica',
    aval: 'Jogo de classificação em grupos e registro no Diário de Bordo (formativa)',
    rec: 'Cartões com exemplos de IA, slides com imagens, projetor, caderno do estudante',
    quadro: [
      'IA — AULA 03: TIPOS DE IA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IA ESTREITA (fraca)',
      '  Faz UMA coisa muito bem',
      '  Ex: Siri, filtro de spam, GPS',
      ' ',
      'IA GERAL (forte)',
      '  Raciocina como humano — não existe ainda',
      ' ',
      'IA FICÇÃO CIENTÍFICA',
      '  HAL 9000, JARVIS (Homem de Ferro)'
    ],
    guia: null, tempos: []
  },
  {
    sem: 4, tri: 1,
    tema: 'IA no Cotidiano — Onde Ela Está?',
    tipo: 'teoria',
    comp: 'Reconhecer a presença da IA em aplicativos e dispositivos do dia a dia',
    hab: 'Mapear coletivamente os momentos do dia em que a IA aparece',
    aval: 'Participação no mapeamento coletivo e registro no Diário de Bordo (formativa)',
    rec: 'Celulares dos alunos ou fichas impressas, quadro e marcadores, slides com exemplos',
    quadro: [
      'IA — AULA 04: IA NO COTIDIANO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '"Caça à IA": liste 5 apps e pesquise',
      '  se há IA em cada um',
      ' ',
      'EXEMPLOS:',
      '  Instagram → algoritmo de relevância',
      '  Netflix → sistema de recomendação',
      '  Google Maps → rotas em tempo real',
      '  WhatsApp → autocomplete',
      ' ',
      'Debate: possível viver um dia sem IA?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 5, tri: 1,
    tema: 'O que é um Algoritmo? As Máquinas Seguem Instruções',
    tipo: 'teoria',
    comp: 'Compreender o conceito de algoritmo e relacioná-lo ao funcionamento das IAs',
    hab: 'Criar algoritmos em linguagem natural para tarefas do cotidiano',
    aval: 'Algoritmo criado em duplas e observação da dinâmica (formativa)',
    rec: 'Espaço para dinâmica, caderno e canetas, slides ilustrativos, objetos simples',
    quadro: [
      'IA — AULA 05: ALGORITMOS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'ALGORITMO = sequência de instruções',
      '  Receita de bolo = algoritmo!',
      '  GPS passo a passo = algoritmo!',
      ' ',
      'Dinâmica "Robô Humano":',
      '  Programador → instruções verbais',
      '  Robô → executa LITERALMENTE',
      '  Sem instrução exata → erro!',
      ' ',
      'Prática: criar algoritmo em linguagem natural'
    ],
    guia: null, tempos: []
  },
  {
    sem: 6, tri: 1,
    tema: 'Como a IA Toma Decisões? Fluxogramas e Lógica SE/ENTÃO',
    tipo: 'pratica',
    comp: 'Entender como sistemas de IA tomam decisões com lógica condicional',
    hab: 'Construir fluxogramas com condições SE/ENTÃO para representar decisões de IA',
    aval: 'Fluxograma em grupo — lógica, criatividade e condições (formativa)',
    rec: 'Papel A3 ou cartolina, canetas coloridas e régua, slides com símbolos de fluxograma',
    quadro: [
      'IA — AULA 06: FLUXOGRAMAS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'LÓGICA SE/ENTÃO:',
      '  SE chovendo → levar guarda-chuva',
      '  SE e-mail tem "promoção" → é spam',
      ' ',
      'SÍMBOLOS DO FLUXOGRAMA:',
      '  Losango → decisão (SE/ENTÃO)',
      '  Retângulo → ação',
      ' ',
      'Atividade: fluxograma "IA de música"',
      '  Incluir ≥3 decisões condicionais'
    ],
    guia: null, tempos: []
  },
  {
    sem: 7, tri: 1,
    tema: 'Robótica e Automação — Máquinas que Agem no Mundo',
    tipo: 'teoria',
    comp: 'Compreender o conceito de robótica e sua relação com a IA',
    hab: 'Diferenciar robótica simples de robótica com IA e analisar casos reais no Brasil',
    aval: 'Folha de análise de notícia sobre robótica entregue ao professor (formativa)',
    rec: 'Vídeos Boston Dynamics e linha de produção (YouTube), notícias impressas sobre robótica no Brasil, projetor',
    quadro: [
      'IA — AULA 07: ROBÓTICA E AUTOMAÇÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Robótica SIMPLES: programação fixa',
      'Robótica com IA: aprende e se adapta',
      ' ',
      'EXEMPLOS:',
      '  Braços robóticos industriais',
      '  Robô cirúrgico Da Vinci',
      '  Drones de entrega',
      '  Roomba | Carro Tesla (autopilot)',
      ' ',
      'Análise: notícia de robótica no Brasil',
      '  Quem se beneficia? Quem pode perder?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 8, tri: 1,
    tema: 'IA na Saúde, Educação e Agronegócio',
    tipo: 'teoria',
    comp: 'Reconhecer aplicações reais de IA em setores fundamentais da sociedade brasileira',
    hab: 'Pesquisar e ensinar exemplos de IA na saúde, educação e agricultura (Jigsaw)',
    aval: 'Atividade Jigsaw e registro no Diário de Bordo (formativa)',
    rec: 'Manchetes impressas, slides com imagens dos setores, celulares para pesquisa',
    quadro: [
      'IA — AULA 08: SETORES DE APLICAÇÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'SAÚDE:',
      '  Diagnóstico por imagem | IA no SUS',
      'EDUCAÇÃO:',
      '  Khan Academy | Duolingo adaptativo',
      '  Detecção de dificuldades de aprendizagem',
      'AGRONEGÓCIO:',
      '  Drones | Sensores | Embrapa usa IA',
      '  Previsão de safra',
      ' ',
      'Jigsaw: cada grupo ensina um setor'
    ],
    guia: null, tempos: []
  },
  {
    sem: 9, tri: 1,
    tema: 'Tendências: IA Generativa, Metaverso e o Futuro',
    tipo: 'teoria',
    comp: 'Conhecer tendências emergentes da IA e refletir sobre o futuro tecnológico',
    hab: 'Debater criticamente sobre automação de profissões e IA generativa',
    aval: 'Texto reflexivo: "Como imagino a IA na minha vida profissional em 2035" (formativa)',
    rec: 'Computador com internet e projetor, ChatGPT / Canva IA / DALL-E, caderno',
    quadro: [
      'IA — AULA 09: IA GENERATIVA E FUTURO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IA GENERATIVA: gera texto, imagem, áudio',
      '  ChatGPT | DALL-E | Midjourney',
      '  Suno | ElevenLabs | Bing Chat',
      ' ',
      'PROMPT: instrução que você dá à IA',
      ' ',
      'Debate estruturado:',
      '  A IA vai substituir professores?',
      '  E artistas? E médicos?',
      ' ',
      'Reflexão escrita: minha vida em 2035'
    ],
    guia: null, tempos: []
  },
  {
    sem: 10, tri: 1,
    tema: 'Revisão da Unidade I — Quiz e Consolidação',
    tipo: 'aval',
    comp: 'Revisar e consolidar os conteúdos da Unidade I de forma lúdica',
    hab: 'Demonstrar compreensão dos conceitos de IA, algoritmos, robótica e IA generativa',
    aval: 'Quiz Kahoot — diagnóstico formativo + ficha de autoavaliação',
    rec: 'Kahoot (celular) ou perguntas impressas, ficha de autoavaliação, quadro',
    quadro: [
      'IA — AULA 10: REVISÃO UNIDADE I',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'QUIZ — 15 questões:',
      '  Conceito e histórico da IA',
      '  IA Fraca vs Forte | Algoritmos',
      '  Fluxogramas | Robótica',
      '  Setores | IA Generativa',
      ' ',
      'AUTOAVALIAÇÃO:',
      '  Aprendi bem...',
      '  Ainda tenho dúvida sobre...',
      '  Quero saber mais sobre...'
    ],
    guia: null, tempos: []
  },

  // ─── UNIDADE II: Como as Máquinas Aprendem? ───────────────
  {
    sem: 11, tri: 1,
    tema: 'Introdução ao Aprendizado de Máquina (Machine Learning)',
    tipo: 'teoria',
    comp: 'Compreender o conceito de Machine Learning e como as máquinas aprendem com dados',
    hab: 'Diferenciar aprendizado supervisionado, não supervisionado e por reforço',
    aval: 'Definição de ML escrita com as próprias palavras + participação na dinâmica (formativa)',
    rec: 'Fotos de gatos e cachorros (slides), placas "CORRETO" e "ERRADO", objetos simples para dinâmica',
    quadro: [
      'IA — AULA 11: MACHINE LEARNING',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'MACHINE LEARNING:',
      '  Máquina aprende PADRÕES a partir de dados',
      '  Sem ser programada para cada caso',
      ' ',
      'TIPOS:',
      '  Supervisionado → aprende com exemplos',
      '  Não supervisionado → agrupa sozinho',
      '  Por reforço → aprende tentativa/erro',
      ' ',
      'Dinâmica: "Treinar um Humano"'
    ],
    guia: null, tempos: []
  },
  {
    sem: 12, tri: 1,
    tema: 'Dados: O Combustível da Inteligência Artificial',
    tipo: 'teoria',
    comp: 'Entender o papel fundamental dos dados no funcionamento dos sistemas de IA',
    hab: 'Identificar padrões em dados simples e refletir sobre privacidade e geração de dados',
    aval: 'Análise de tabela de dados e registro reflexivo no Diário de Bordo (formativa)',
    rec: 'Tabela de dados fictícios impressa, slides com estatísticas de volume de dados, quadro',
    quadro: [
      'IA — AULA 12: DADOS E IA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Dados que você gera hoje:',
      '  Mensagens | Curtidas | Localização',
      '  Pesquisas | Compras | Músicas',
      ' ',
      'TIPOS DE DADOS:',
      '  Estruturados → tabelas',
      '  Não estruturados → fotos, textos, vídeos',
      ' ',
      'Quanto mais dados → melhor o modelo',
      'Netflix: bilhões de views → recomendação'
    ],
    guia: null, tempos: []
  },
  {
    sem: 13, tri: 1,
    tema: 'Teachable Machine — Criando um Modelo de ML na Prática',
    tipo: 'pratica',
    comp: 'Criar e treinar um modelo de Machine Learning com Google Teachable Machine',
    hab: 'Vivenciar coleta de dados, treino e teste de modelo de ML na prática',
    aval: 'Modelo criado e testado + registro de observações no caderno (formativa/prática)',
    rec: 'Google Teachable Machine (internet), celulares ou computadores com câmera, Wi-Fi da escola',
    quadro: [
      'IA — AULA 13: TEACHABLE MACHINE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'teachablemachine.withgoogle.com',
      ' ',
      'ETAPAS:',
      '  1. Coletar dados (≥30 fotos/classe)',
      '  2. Treinar o modelo',
      '  3. Testar em tempo real',
      ' ',
      'Experimento:',
      '  O que acontece com poucos dados?',
      '  E com dados de baixa qualidade?'
    ],
    guia: null, tempos: []
  },

  // ─── 2º TRIMESTRE — UNIDADE II (cont.) e III ──────────────
  {
    sem: 14, tri: 2,
    tema: 'Reconhecimento de Imagens e Visão Computacional',
    tipo: 'pratica',
    comp: 'Entender como a IA reconhece imagens e vídeos e identificar aplicações práticas',
    hab: 'Explorar o Google Lens e debater usos éticos do reconhecimento facial',
    aval: 'Registro dos experimentos com Google Lens e participação no debate ético (formativa)',
    rec: 'Celulares com Google Lens, projetor, objetos variados na sala, planta em vaso (opcional)',
    quadro: [
      'IA — AULA 14: VISÃO COMPUTACIONAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Como a IA "enxerga":',
      '  Pixels → grade de valores numéricos',
      ' ',
      'APLICAÇÕES:',
      '  Face ID | Diagnóstico de câncer por foto',
      '  OCR: câmera lê texto | Carro autônomo',
      '  Moderação de conteúdo em redes sociais',
      ' ',
      'Experimento: Google Lens na sala',
      'Debate: câmeras faciais em escolas públicas?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 15, tri: 2,
    tema: 'Processamento de Linguagem Natural — Como a IA Entende Texto',
    tipo: 'pratica',
    comp: 'Compreender o funcionamento básico do PLN e explorar ferramentas que o utilizam',
    hab: 'Testar PLN com Google Tradutor, ChatGPT e corretor automático na prática',
    aval: 'Registro dos experimentos e síntese coletiva sobre PLN (formativa)',
    rec: 'Celulares com internet, Google Tradutor, ChatGPT ou Gemini, slides com frases ambíguas',
    quadro: [
      'IA — AULA 15: PLN',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PLN = Processamento de Linguagem Natural',
      '  IA entende e gera linguagem humana',
      ' ',
      'APLICAÇÕES:',
      '  Google Tradutor | Corretor automático',
      '  Assistentes de voz | ChatGPT',
      '  Análise de sentimentos',
      ' ',
      'Frases ambíguas:',
      '  "Vi o homem com o telescópio"',
      '  → Como a máquina interpreta?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 16, tri: 2,
    tema: 'Assistentes Virtuais — Alexa, Siri e Chatbots',
    tipo: 'pratica',
    comp: 'Analisar o funcionamento dos assistentes virtuais e chatbots, suas capacidades e limites',
    hab: 'Criar um fluxograma de chatbot simulando atendimento automatizado',
    aval: 'Fluxograma do chatbot criado em grupo (formativa)',
    rec: 'Celular com Google Assistente, papel e canetas para o fluxograma, slides, projetor',
    quadro: [
      'IA — AULA 16: ASSISTENTES E CHATBOTS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'ASSISTENTE VIRTUAL:',
      '  Voz → PLN → Base de conhecimento',
      '  → Síntese de voz → Resposta',
      ' ',
      'CHATBOT POR REGRAS: respostas fixas',
      'CHATBOT COM IA: aprende com conversas',
      '  Atendimento bancário | SAC | Apps',
      ' ',
      'Roleplay: "Chatbot de Papel"',
      '  Fluxo de atendimento: pizzaria/escola'
    ],
    guia: null, tempos: []
  },
  {
    sem: 17, tri: 2,
    tema: "Sistemas de Recomendação — Por Que o YouTube 'Me Conhece'?",
    tipo: 'teoria',
    comp: 'Compreender como os sistemas de recomendação funcionam e seus efeitos no comportamento',
    hab: 'Identificar a bolha de filtro pessoal e refletir sobre suas implicações',
    aval: 'Mapa da bolha de filtro individual e registro no Diário de Bordo (formativa)',
    rec: 'Celulares com acesso ao YouTube, papel para mapeamento, slides com infográfico dos algoritmos',
    quadro: [
      'IA — AULA 17: SISTEMAS DE RECOMENDAÇÃO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'FILTRAGEM COLABORATIVA:',
      '  "Usuários parecidos com você..."',
      'FILTRAGEM POR CONTEÚDO:',
      '  "Você gostou de X → vai gostar de Y"',
      ' ',
      'BOLHA DE FILTRO:',
      '  IA só mostra o que você já acredita',
      ' ',
      'Atividade: 5 canais × 5 temas mais assistidos',
      '  Compare com colegas — as bolhas diferem?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 18, tri: 2,
    tema: 'IA e Criatividade — Arte, Música e Texto Gerados por IA',
    tipo: 'pratica',
    comp: 'Explorar ferramentas de IA generativa em arte, música e escrita criativa',
    hab: 'Criar imagens e textos com IA e refletir criticamente sobre autoria e criatividade',
    aval: 'Criação produzida e reflexão sobre autoria (formativa — pode integrar portfólio)',
    rec: 'Canva IA, ChatGPT / Gemini (internet), celulares ou computadores, projetor para galeria',
    quadro: [
      'IA — AULA 18: IA E CRIATIVIDADE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IA PODE CRIAR:',
      '  Imagens: Canva IA | DALL-E | Midjourney',
      '  Músicas: Suno',
      '  Textos e histórias: ChatGPT',
      '  Vídeos: RunwayML',
      ' ',
      'PROMPT: instrução que você dá à IA',
      ' ',
      'Reflexão: Isso é arte?',
      '  Quem é o autor — você ou a IA?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 19, tri: 2,
    tema: 'Limitações e Erros da IA — Quando as Máquinas Falham',
    tipo: 'teoria',
    comp: 'Identificar as principais limitações dos sistemas de IA e desenvolver postura crítica',
    hab: 'Testar limites de ferramentas de IA e documentar erros encontrados na prática',
    aval: 'Registro dos erros encontrados e síntese no Diário de Bordo (formativa)',
    rec: 'Slides com galeria de erros de IA, celulares com acesso à internet, caderno',
    quadro: [
      'IA — AULA 19: LIMITAÇÕES DA IA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PRINCIPAIS LIMITAÇÕES:',
      '  1. Precisa de muitos dados',
      '  2. Só funciona para o que foi treinada',
      '  3. Não tem senso comum',
      '  4. Reproduz preconceitos dos dados',
      '  5. "Alucina": inventa informações!',
      ' ',
      'Investigação: tente enganar a IA',
      '  ChatGPT | Tradutor | Google Lens'
    ],
    guia: null, tempos: []
  },
  {
    sem: 20, tri: 2,
    tema: 'Revisão da Unidade II — Avaliação Escrita e Consolidação',
    tipo: 'aval',
    comp: 'Revisar e consolidar os conteúdos da Unidade II por avaliação escrita',
    hab: 'Demonstrar compreensão de ML, dados, PLN, visão computacional e recomendação',
    aval: 'Mini-avaliação escrita (somativa — 25% da nota)',
    rec: 'Avaliação impressa, quadro e marcadores, caderno do estudante',
    quadro: [
      'IA — AULA 20: REVISÃO UNIDADE II',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'AVALIAÇÃO — 8 questões:',
      '  ML: conceito e 3 tipos',
      '  Dados: papel e importância',
      '  PLN: exemplos e funcionamento',
      '  Visão computacional: aplicações',
      '  Sistemas de recomendação',
      '  Limitações da IA',
      ' ',
      'Nuvem de palavras coletiva',
      'Próxima unidade: Ética e Sociedade'
    ],
    guia: null, tempos: []
  },

  // ─── UNIDADE III: IA, Ética e Sociedade ───────────────────
  {
    sem: 21, tri: 2,
    tema: 'Privacidade de Dados — O que Sabem Sobre Mim?',
    tipo: 'teoria',
    comp: 'Compreender privacidade digital e identificar dados coletados por aplicativos',
    hab: 'Auditar permissões de apps do celular e refletir sobre riscos',
    aval: 'Análise dos apps e registro de comprometimento no Diário de Bordo (formativa)',
    rec: 'Celulares dos alunos, slides com capturas de tela de permissões e termos de uso, projetor',
    quadro: [
      'IA — AULA 21: PRIVACIDADE DIGITAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'TIPOS DE DADOS PESSOAIS:',
      '  Identificação | Localização',
      '  Comportamento | Biométricos',
      ' ',
      'Apps coletam dados mesmo sem uso ativo',
      'Caso Cambridge Analytica + Facebook',
      ' ',
      'Auditoria de privacidade:',
      '  Instagram | TikTok | WhatsApp',
      '  → Quais dados? Quais permissões?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 22, tri: 2,
    tema: 'LGPD — Meus Dados Têm Proteção?',
    tipo: 'teoria',
    comp: 'Conhecer a Lei Geral de Proteção de Dados e os direitos do cidadão brasileiro',
    hab: 'Analisar situações-problema de violação da LGPD e identificar soluções',
    aval: 'Análise das situações-problema em grupo (formativa)',
    rec: 'Vídeo sobre LGPD (YouTube — Governo Federal ou Procon), cartões com situações-problema',
    quadro: [
      'IA — AULA 22: LGPD',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'LGPD — Lei 13.709/2018',
      '  Inspirada no GDPR europeu',
      ' ',
      'SEUS DIREITOS:',
      '  Confirmar coleta | Acessar dados',
      '  Corrigir | Excluir | Portabilidade',
      '  Revogar consentimento',
      ' ',
      'Quem deve cumprir:',
      '  Empresas | Governo | Escolas',
      ' ',
      'Estudo de casos: houve violação?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 23, tri: 2,
    tema: 'Viés Algorítmico — Quando a IA Discrimina',
    tipo: 'teoria',
    comp: 'Compreender o conceito de viés algorítmico e seus impactos sociais',
    hab: 'Simular seleção com critérios algorítmicos e identificar injustiças estruturais',
    aval: 'Participação na simulação e registro reflexivo no Diário de Bordo (formativa)',
    rec: 'Slides com casos documentados de viés, fichas de candidatos fictícios, caderno',
    quadro: [
      'IA — AULA 23: VIÉS ALGORÍTMICO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CASOS REAIS:',
      '  Reconhecimento facial: 34% mais erro',
      '  em mulheres negras (MIT Media Lab)',
      '  Amazon IA discriminou mulheres',
      '  Crédito bancário penalizou periferias',
      ' ',
      'Por quê? Dados refletem o mundo como É,',
      '  não como deveria ser',
      ' ',
      'Simulação: "Juiz Robot"'
    ],
    guia: null, tempos: []
  },
  {
    sem: 24, tri: 2,
    tema: 'Fake News, Deepfakes e Desinformação na Era da IA',
    tipo: 'pratica',
    comp: 'Compreender como a IA pode criar e disseminar desinformação',
    hab: 'Usar ferramentas de checagem para verificar notícias e imagens suspeitas',
    aval: 'Processo de checagem documentado e metodologia do grupo (formativa)',
    rec: 'Imagens e vídeos de deepfakes selecionados, notícias impressas (2 reais, 2 falsas), celulares',
    quadro: [
      'IA — AULA 24: FAKE NEWS E DEEPFAKES',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'DEEPFAKE: vídeo/áudio falsificado com IA',
      ' ',
      'Impacto:',
      '  Eleições | Saúde pública',
      '  Desinformação sobre vacinas',
      ' ',
      'FERRAMENTAS DE CHECAGEM:',
      '  Google Reverse Image Search',
      '  Agência Lupa | G1 Fato ou Fake',
      ' ',
      'Prática: checar 4 notícias (2 reais, 2 falsas)'
    ],
    guia: null, tempos: []
  },
  {
    sem: 25, tri: 2,
    tema: 'Vigilância Digital e Reconhecimento Facial',
    tipo: 'teoria',
    comp: 'Compreender as implicações éticas e legais da vigilância digital com IA',
    hab: 'Debater o dilema segurança vs. privacidade no reconhecimento facial',
    aval: 'Participação no tribunal simulado e posição fundamentada no Diário de Bordo (formativa)',
    rec: 'Slides com casos reais de reconhecimento facial no Brasil, roteiro do debate',
    quadro: [
      'IA — AULA 25: VIGILÂNCIA DIGITAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Reconhecimento facial no Brasil:',
      '  Aeroportos | Estádios | Carnaval',
      '  Cidades inteligentes | Escolas',
      ' ',
      'DILEMA:',
      '  + Segurança / Combate ao crime',
      '  - Privacidade / Falsos positivos',
      '    Pessoas presas injustamente',
      ' ',
      'Tribunal Simulado:',
      '  Câmeras nas escolas — favor ou contra?'
    ],
    guia: null, tempos: []
  },
  {
    sem: 26, tri: 2,
    tema: 'IA e Acessibilidade — Tecnologia que Inclui',
    tipo: 'teoria',
    comp: 'Reconhecer como a IA promove inclusão de pessoas com deficiência',
    hab: 'Pesquisar e apresentar tecnologias de IA para acessibilidade disponíveis no Brasil',
    aval: 'Apresentação do grupo e ideia individual de produto acessível (formativa)',
    rec: 'Vídeo sobre IA e acessibilidade (Hand Talk), celulares para pesquisa, projetor',
    quadro: [
      'IA — AULA 26: IA E ACESSIBILIDADE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IA PARA INCLUSÃO:',
      '  Reconhecimento de Libras em tempo real',
      '  Leitores de tela inteligentes (cegos)',
      '  Legendas automáticas (surdos)',
      '  Comunicação alternativa (paralisia)',
      '  Detecção de dislexia em crianças',
      '  Hand Talk — app BRASILEIRO!',
      ' ',
      'Desafio: "Se eu criasse uma IA para',
      '  ajudar uma pessoa com deficiência..."'
    ],
    guia: null, tempos: []
  },
  {
    sem: 27, tri: 2,
    tema: 'Quem é Responsável Quando a IA Erra?',
    tipo: 'teoria',
    comp: 'Refletir sobre responsabilidade ética e legal nos sistemas de IA',
    hab: 'Simular julgamento sobre responsabilidade em acidentes causados por IA',
    aval: 'Participação no julgamento simulado e sentença individual fundamentada (formativa)',
    rec: 'Slides com 3 casos reais, roteiros dos papéis para o julgamento, caderno',
    quadro: [
      'IA — AULA 27: RESPONSABILIDADE NA IA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CASOS:',
      '  Carro autônomo atropelou pedestre',
      '  IA médica diagnosticou errado',
      '  Algoritmo negou crédito indevido',
      ' ',
      'Quem é responsável?',
      '  Desenvolvedor | Empresa | Usuário',
      '  IA não tem personalidade jurídica',
      ' ',
      'PL 2.338/2023 — Regulação da IA no Brasil',
      'Conceito de "IA de alto risco"'
    ],
    guia: null, tempos: []
  },

  // ─── 3º TRIMESTRE — UNIDADE III (final) e IV ──────────────
  {
    sem: 28, tri: 3,
    tema: 'IA e Saúde Mental — Redes Sociais e Bem-Estar',
    tipo: 'teoria',
    comp: 'Analisar o impacto dos algoritmos das redes sociais na saúde mental dos adolescentes',
    hab: 'Desenvolver consciência sobre uso da tecnologia e estratégias de bem-estar digital',
    aval: 'Participação no autodiagnóstico e contribuição ao guia de bem-estar (formativa)',
    rec: 'Slides com estatísticas de uso de redes sociais, formulário de autodiagnóstico impresso',
    quadro: [
      'IA — AULA 28: IA E SAÚDE MENTAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Adolescentes no Brasil: 5-7h/dia no celular',
      ' ',
      'ALGORITMOS PROJETADOS PARA:',
      '  Maximizar tempo de uso (dopamina)',
      '  Doomscrolling',
      '  Filtros IA distorcem percepção corporal',
      ' ',
      'Autodiagnóstico crítico (sem julgamento)',
      '"Guia de Bem-Estar Digital":',
      '  Cada aluno contribui com 1 dica'
    ],
    guia: null, tempos: []
  },
  {
    sem: 29, tri: 3,
    tema: 'Seminário de Ética em IA — Apresentações dos Grupos',
    tipo: 'aval',
    comp: 'Desenvolver argumentação oral e pensamento crítico sobre ética na IA',
    hab: 'Apresentar posição fundamentada sobre tema ético em IA para a turma',
    aval: 'Apresentação do seminário (somativa — argumentação, posição crítica, clareza)',
    rec: 'Projetor, cronômetro visível, rubrica de avaliação do seminário impressa',
    quadro: [
      'IA — AULA 29: SEMINÁRIO DE ÉTICA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'TEMAS DO SEMINÁRIO:',
      '  1. IA deve ter direitos?',
      '  2. Vigilância total × segurança',
      '  3. IA nas eleições — regular?',
      '  4. Robôs podem substituir professores?',
      '  5. IA para menores — restrições?',
      ' ',
      'Formato: 5 min por grupo',
      '  + 2 min de perguntas da turma',
      ' ',
      'Avaliação: argumentação e posição crítica'
    ],
    guia: null, tempos: []
  },
  {
    sem: 30, tri: 3,
    tema: 'Revisão da Unidade III — Consolidação Ética',
    tipo: 'aval',
    comp: 'Revisar e consolidar os temas éticos da Unidade III de forma criativa',
    hab: 'Escrever carta com pedidos éticos concretos para desenvolvedores de IA',
    aval: 'Carta Aberta individual — mínimo 15 linhas, 3 pedidos éticos (formativa / portfólio)',
    rec: 'Folha de papel para a carta, caderno, fita adesiva para expor as cartas na sala',
    quadro: [
      'IA — AULA 30: REVISÃO UNIDADE III',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Quiz ético — dilemas sem resposta certa:',
      '  "Você monitoraria seu filho de 13 anos?"',
      '  "Privacidade ou segurança?"',
      ' ',
      'Carta Aberta aos Desenvolvedores de IA:',
      '  Mínimo 15 linhas',
      '  3 pedidos éticos concretos',
      '  Ex: "Exigimos transparência nos',
      '       dados de treinamento"',
      ' ',
      'Exposição das cartas na sala'
    ],
    guia: null, tempos: []
  },

  // ─── UNIDADE IV: IA, Mundo do Trabalho e Projeto Final ────
  {
    sem: 31, tri: 3,
    tema: 'IA e o Futuro do Trabalho — O que Muda?',
    tipo: 'teoria',
    comp: 'Analisar os impactos da IA no mercado de trabalho e identificar novas oportunidades',
    hab: 'Criar mapa do futuro profissional pessoal relacionado às tendências de automação',
    aval: 'Mapa do Futuro Profissional individual (formativa)',
    rec: 'Dados do Fórum Econômico Mundial (slides), folha para o mapa, celulares para pesquisa',
    quadro: [
      'IA — AULA 31: IA E TRABALHO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Fórum Econômico Mundial:',
      '  85 mi empregos substituídos por IA',
      '  97 mi novos empregos surgirão',
      ' ',
      'MAIOR RISCO: caixa, telemarketing, motorista',
      'MENOR RISCO: psicólogo, professor, artista',
      ' ',
      'NOVAS PROFISSÕES:',
      '  Engenheiro de prompts',
      '  Especialista em ética de IA',
      '  Curador de dados'
    ],
    guia: null, tempos: []
  },
  {
    sem: 32, tri: 3,
    tema: 'Habilidades Humanas na Era da IA — O que Só Nós Fazemos?',
    tipo: 'teoria',
    comp: 'Identificar habilidades especificamente humanas que a IA não consegue replicar',
    hab: 'Criar Manifesto Pessoal com 5 habilidades humanas e exemplos da própria vida',
    aval: 'Manifesto Pessoal individual — formato livre (formativa / portfólio projeto final)',
    rec: 'ChatGPT aberto no projetor, materiais de arte (papel, canetas coloridas, revistas)',
    quadro: [
      'IA — AULA 32: HABILIDADES HUMANAS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'IA vs. Humano — quem sai melhor?',
      '  Piada sobre o que aconteceu hoje?',
      '  Consolar amigo triste?',
      '  Solução improvisada na sala?',
      ' ',
      '4 COMPETÊNCIAS DO SÉCULO XXI:',
      '  Criatividade | Colaboração',
      '  Pensamento crítico | Comunicação',
      ' ',
      'Manifesto: 5 habilidades que só EU tenho'
    ],
    guia: null, tempos: []
  },
  {
    sem: 33, tri: 3,
    tema: 'Como Usar a IA de Forma Produtiva e Responsável',
    tipo: 'pratica',
    comp: 'Desenvolver habilidades práticas para usar IA generativa de forma eficaz e ética',
    hab: 'Escrever prompts eficazes e usar IA como assistente na produção escolar',
    aval: 'Reflexão: o que a IA fez bem / o que precisei corrigir / o que só eu poderia adicionar (formativa)',
    rec: 'ChatGPT / Gemini (internet), celulares ou computadores, tarefas reais dos alunos',
    quadro: [
      'IA — AULA 33: USO PRODUTIVO DA IA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PROMPT EFICAZ:',
      '  Vago: "escreva sobre IA"',
      '  Bom: "Explique IA para um estudante',
      '  de 15 anos, em 3 parágrafos, com',
      '  linguagem simples"',
      ' ',
      'LIMITES:',
      '  NÃO use IA para plágio',
      '  IA = ASSISTENTE, não substituto',
      ' ',
      'Como citar IA em trabalhos escolares'
    ],
    guia: null, tempos: []
  },
  {
    sem: 34, tri: 3,
    tema: 'Ser Cidadão Digital na Era da IA',
    tipo: 'teoria',
    comp: 'Consolidar o conceito de cidadania digital articulando todos os aprendizados da disciplina',
    hab: 'Identificar pilares da cidadania digital e elaborar compromisso pessoal concreto',
    aval: 'Participação no jogo de situações e Termo de Compromisso Digital (formativa)',
    rec: 'Slides com os 9 pilares da cidadania digital, cartas de situações, Termo de Compromisso impresso',
    quadro: [
      'IA — AULA 34: CIDADANIA DIGITAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '9 PILARES DA CIDADANIA DIGITAL:',
      '  Acesso | Comércio | Comunicação',
      '  Letramento | Etiqueta',
      '  Saúde e bem-estar | Segurança',
      '  Direitos e responsabilidades',
      '  Autocuidado',
      ' ',
      'Jogo de situações digitais',
      'Termo de Compromisso Digital — 3 ações'
    ],
    guia: null, tempos: []
  },
  {
    sem: 35, tri: 3,
    tema: 'Lançamento e Planejamento do Projeto Final',
    tipo: 'projeto',
    comp: 'Planejar o projeto final da disciplina em grupos de 3-4 alunos',
    hab: 'Definir tema, formato, mensagem principal, divisão de tarefas e cronograma',
    aval: 'Plano do Projeto entregue e validado pelo professor (formativa — pré-requisito)',
    rec: 'Rubrica do projeto final, ficha de Plano do Projeto, lista de temas disponíveis',
    quadro: [
      'IA — AULA 35: PROJETO FINAL',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'FORMATOS POSSÍVEIS:',
      '  Infográfico | Podcast',
      '  Vídeo (≤3 min) | Slides | Cartaz',
      ' ',
      'TEMAS DISPONÍVEIS:',
      '  IA e saúde | deepfakes | viés',
      '  privacidade | IA e trabalho',
      '  IA generativa | acessibilidade',
      '  robótica | IA e agroecologia',
      ' ',
      'Plano: tema, formato, tarefas, cronograma'
    ],
    guia: null, tempos: []
  },
  {
    sem: 36, tri: 3,
    tema: 'Produção do Projeto Final — Aula de Trabalho I',
    tipo: 'projeto',
    comp: 'Desenvolver pesquisa e conteúdo do projeto final com orientação do professor',
    hab: 'Selecionar fontes confiáveis e produzir rascunho com roteiro estruturado',
    aval: 'Acompanhamento do processo — engajamento e progresso (formativa)',
    rec: 'Celulares e/ou computadores com internet, Canva, gravador para podcast, ficha de acompanhamento',
    quadro: [
      'IA — AULA 36: PRODUÇÃO I',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'META ao final desta aula:',
      '  Tema definido com clareza',
      '  ≥3 fontes confiáveis levantadas',
      '  Roteiro ou esboço do produto',
      ' ',
      'Status Check:',
      '  O que fizemos hoje',
      '  O que falta fazer',
      '  Precisamos de ajuda com: ___'
    ],
    guia: null, tempos: []
  },
  {
    sem: 37, tri: 3,
    tema: 'Produção do Projeto Final — Aula de Trabalho II',
    tipo: 'projeto',
    comp: 'Avançar na produção do produto final com foco em qualidade e clareza da mensagem',
    hab: 'Produzir material final e dar/receber feedback estruturado de pares',
    aval: 'Feedback de pares documentado e produto em andamento (formativa)',
    rec: 'Celulares e/ou computadores, Canva, CapCut, Anchor (podcast), fone de ouvido',
    quadro: [
      'IA — AULA 37: PRODUÇÃO II',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'META do grupo para hoje: "Teremos ___ pronto"',
      ' ',
      'Perguntas orientadoras:',
      '  A mensagem está clara para quem',
      '  não sabe nada sobre o tema?',
      '  O que você removeria?',
      ' ',
      'Feedback de pares:',
      '  1 ponto forte',
      '  1 sugestão de melhoria'
    ],
    guia: null, tempos: []
  },
  {
    sem: 38, tri: 3,
    tema: 'Produção do Projeto Final — Aula de Trabalho III e Ensaio',
    tipo: 'projeto',
    comp: 'Finalizar o produto e ensaiar a apresentação oral para a turma',
    hab: 'Revisar conteúdo, checar fontes e praticar oralidade para apresentação',
    aval: 'Produto final entregue ao professor (somativa — vale 30% da nota)',
    rec: 'Celulares e/ou computadores, cronômetro, checklist de qualidade impresso',
    quadro: [
      'IA — AULA 38: PRODUÇÃO III + ENSAIO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CHECKLIST FINAL:',
      '  Conteúdo revisado e correto?',
      '  Fontes verificadas?',
      '  Qualidade visual/sonora OK?',
      ' ',
      'ENSAIO (3-5 min):',
      '  Quem fala o quê?',
      '  Postura | Volume | Contato visual',
      '  Não ler do papel',
      ' ',
      'Entrega do produto ao professor'
    ],
    guia: null, tempos: []
  },
  {
    sem: 39, tri: 3,
    tema: 'Apresentação dos Projetos Finais',
    tipo: 'aval',
    comp: 'Apresentar o projeto final desenvolvendo comunicação oral e escuta ativa',
    hab: 'Comunicar tema de IA com clareza para a turma e responder perguntas',
    aval: 'Apresentação oral (somativa — 30%: clareza, criatividade, conteúdo, oralidade)',
    rec: 'Projetor e caixas de som, ficha de avaliação de pares, cronômetro, cédulas de votação anônima',
    quadro: [
      'IA — AULA 39: APRESENTAÇÕES FINAIS',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Formato: 4 min por grupo',
      '  + 1 min de perguntas da turma',
      ' ',
      'AVALIAÇÃO (rubrica):',
      '  Clareza | Criatividade',
      '  Conteúdo | Oralidade',
      ' ',
      'VOTAÇÃO DA TURMA (anônima):',
      '  Mais informativo',
      '  Mais criativo | Mais relevante'
    ],
    guia: null, tempos: []
  },
  {
    sem: 40, tri: 3,
    tema: 'Encerramento — Síntese, Autoavaliação e Celebração',
    tipo: 'aval',
    comp: 'Encerrar a disciplina com síntese reflexiva do percurso e celebração das aprendizagens',
    hab: 'Autoavaliar o percurso e projetar o futuro com consciência crítica sobre IA',
    aval: 'Ficha de autoavaliação final (formativa) e encerramento celebrativo',
    rec: 'Quadro e marcadores coloridos, ficha de autoavaliação impressa, envelopes lacráveis, cartões do professor',
    quadro: [
      'IA — AULA 40: ENCERRAMENTO',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Linha do Tempo da Turma:',
      '  Um tema marcante de cada aula',
      ' ',
      'AUTOAVALIAÇÃO:',
      '  Quais competências desenvolvi?',
      '  O que mudou no meu uso da IA?',
      '  Participação (1-10) — por quê?',
      ' ',
      'Carta para o Futuro — abrir em 2028:',
      '  "Em 2028, a IA estará assim..."',
      '  "Minhas preocupações são..."'
    ],
    guia: null, tempos: []
  }
];
