// ============================================================
// SEQUÊNCIA DIDÁTICA — Design e Acessibilidade — 3º Ano
// 40 semanas letivas — 3 trimestres — SEDUC-PI PPC 2024
// Edite os temas, competências e conteúdos conforme necessário
// ============================================================

const AULAS_DESIGN = [
  // ─── 1º TRIMESTRE ─────────────────────────────────────────
  {
    sem: 1, tri: 1,
    tema: 'Fundamentos do design: princípios visuais, composição e hierarquia',
    tipo: 'teoria',
    comp: 'Compreender os princípios fundamentais do design visual aplicados à web',
    hab: 'Identificar alinhamento, contraste, repetição e proximidade em layouts reais',
    aval: 'Análise de interfaces reais com identificação dos princípios (AQL — participação)',
    rec: 'Projetor, lousa, exemplos de sites e apps, slides com comparações',
    quadro: [
      'DESIGN — PRINCÍPIOS VISUAIS — SEM. 1',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PRINCÍPIOS (C.R.A.P.):',
      '  Contraste   — destaque pelo diferente',
      '  Repetição   — coerência visual',
      '  Alinhamento — ordem e organização',
      '  Proximidade — agrupar o relacionado',
      ' ',
      'HIERARQUIA VISUAL:',
      '  Tamanho | Cor | Posição | Peso',
      '  O olho segue do maior ao menor'
    ],
    guia: [
      { num: 1, cor: '#7B2D8B', bg: '#F3E8F9', titulo: 'Abertura — o que é design? (10 min)', desc: 'Mostre no projetor dois sites lado a lado: um bem projetado (ex: Apple, Airbnb) e um mal projetado (ex: site institucional antigo). Pergunte: "O que faz um parecer melhor?" Anote as respostas no quadro sem corrigir. Objetivo: ativar percepção visual dos alunos antes do conceito.', dica: 'Não corrija agora — ao fim da aula volte às respostas e relacione com os princípios C.R.A.P. aprendidos.', dicaBg: '#F3E8F9', dicaCor: '#5A1F68' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Princípios C.R.A.P. — conceito e exemplos (15 min)', desc: 'Explique cada princípio com exemplos visuais no projetor: Contraste (texto preto em fundo branco vs cinza claro), Repetição (botões com mesmo estilo), Alinhamento (grade no layout), Proximidade (campos de formulário agrupados). Use o mesmo site para mostrar todos os quatro princípios.', dica: 'Crie o acrônimo no quadro: C.R.A.P. — os alunos riem e memorizam mais facilmente.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Hierarquia visual — como o olho lê (10 min)', desc: 'Mostre um cartaz ou página web. Pergunte: "Qual elemento você viu primeiro? Segundo?" Explique que a hierarquia guia o olhar pelo tamanho, cor, negrito e posição. Desenhe no quadro uma página com H1, H2, parágrafo e botão, mostrando como o peso visual cria ordem de leitura.', dica: '"O designer não decora — ele dirige o olhar do usuário como um diretor de cinema dirige a atenção do espectador."', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Atividade de análise (20 min)', desc: 'Distribua (ou projete) 3 capturas de tela de interfaces diferentes. Cada aluno identifica e anota: qual princípio C.R.A.P. está presente ou ausente em cada uma, e como a hierarquia visual está organizada. Peça que 2-3 alunos compartilhem. Anote participação (AQL).', dica: 'AQL — Participação: registre quem compartilhou análises. Use Google Imagens "bad website design" para exemplos ruins.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese e tarefa (5 min)', desc: 'Síntese: "Design não é estética — é comunicação. Os princípios C.R.A.P. são ferramentas para guiar o usuário." Tarefa: tirar print de um site que usa bem a hierarquia visual e outro que usa mal, justificando a escolha.', dica: '"Na próxima aula: cores. Vocês vão entender por que o McDonald\'s usa amarelo e vermelho juntos."', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Abertura', t: '10 min', bg: '#F3E8F9', c: '#7B2D8B' },
      { label: 'C.R.A.P.', t: '15 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: 'Hierarquia', t: '10 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Atividade', t: '20 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '5 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  {
    sem: 2, tri: 1,
    tema: 'Teoria das cores: círculo cromático, harmonia, contraste e psicologia das cores',
    tipo: 'teoria',
    comp: 'Aplicar teoria das cores na criação de paletas harmônicas para interfaces web',
    hab: 'Identificar esquemas de cores (análoga, complementar, triádica) e criar paletas',
    aval: 'Paleta de cores para uma marca fictícia com justificativa (AQL — produção)',
    rec: 'Laboratório, Figma ou Coolors.co, projetor, roda de cores impressa',
    quadro: [
      'TEORIA DAS CORES — SEM. 2',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CÍRCULO CROMÁTICO:',
      '  Primárias:   Vermelho | Amarelo | Azul',
      '  Secundárias: Laranja | Verde | Roxo',
      ' ',
      'ESQUEMAS DE HARMONIA:',
      '  Análogo:      cores vizinhas',
      '  Complementar: cores opostas',
      '  Triádico:     3 cores equidistantes',
      ' ',
      'PSICOLOGIA: Azul = confiança',
      '  Verde = saúde | Vermelho = urgência'
    ],
    guia: [
      { num: 1, cor: '#7B2D8B', bg: '#F3E8F9', titulo: 'Retomada da tarefa (5 min)', desc: 'Peça 2 alunos para mostrar os prints da tarefa. Registre quem trouxe (AQL participação). Conecte: "Hoje entendemos POR QUE aquele site parecia errado na escolha de cores." Abra o Coolors.co no projetor.', dica: 'Registre quem trouxe a tarefa — participação AQL (30%).', dicaBg: '#F3E8F9', dicaCor: '#5A1F68' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Círculo cromático e esquemas (15 min)', desc: 'Mostre o círculo cromático no projetor. Explique primárias, secundárias e terciárias. Demonstre cada esquema no Coolors.co ao vivo: selecione uma cor, mude para modo Complementar, Análogo, Triádico. Mostre como grandes marcas usam esses esquemas (Instagram = gradiente análogo; Pepsi = complementar azul/vermelho).', dica: 'Use o site de paletas da Adobe Color (color.adobe.com) para mostrar o círculo interativo — mais visual que slides.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Psicologia das cores + contraste (10 min)', desc: 'Explique que cores comunicam emoções e que a escolha deve ser estratégica. Mostre tabela: Azul = confiança/tech (bancos, redes sociais); Verde = saúde/natureza; Vermelho = urgência/promoção; Amarelo = atenção/otimismo. Depois mostre contraste de luminosidade: ferramenta de contraste WCAG no Figma ou contrast-ratio.com.', dica: '"O azul do Facebook foi escolhido porque Zuckerberg é daltônico para vermelho e verde — curiosidade real que prende atenção."', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Prática — criar paleta para marca fictícia (25 min)', desc: 'Desafio: criar uma paleta de 5 cores (primária, secundária, destaque, fundo, texto) para uma marca fictícia escolhida pelo aluno (clínica, app de esportes, loja de games, escola). Usar Coolors.co ou Figma. Escrever justificativa de 3 linhas explicando as escolhas. Anote quem entrega (AQL — produção 40%).', dica: 'AQL: registre quem entregou a paleta com justificativa. Dica para os alunos: comecem pelo azul ou verde se não souberem por onde iniciar.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese (5 min)', desc: 'Mostre 2-3 paletas no projetor. Elogie as justificativas. Síntese: "Cor não é gosto pessoal — é decisão estratégica baseada em emoção, contraste e harmonia." Conecte: "Na próxima aula: tipografia — outro elemento que comunica antes de ser lido."', dica: '"A Netflix usa vermelho sobre preto porque o contraste alto cria urgência e excitação — isso é design consciente."', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Retomada', t: '5 min', bg: '#F3E8F9', c: '#7B2D8B' },
      { label: 'Círculo/Harmonia', t: '15 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: 'Psicologia/Contraste', t: '10 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Prática', t: '25 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '5 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  { sem: 3, tri: 1, tema: 'Tipografia: famílias tipográficas, legibilidade e hierarquia tipográfica', tipo: 'pratica', comp: 'Selecionar e aplicar tipografias adequadas para interfaces web acessíveis', hab: 'Distinguir serif, sans-serif e display e criar hierarquia tipográfica com Google Fonts', aval: 'Layout com 2 fontes e hierarquia H1/H2/body aplicada (AQL — produção)', rec: 'Laboratório, Figma, fonts.google.com', quadro: ['TIPOGRAFIA — SEM. 3','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','FAMÍLIAS:','  Serif:     Times New Roman, Georgia','  Sans-Serif: Inter, Roboto, Poppins','  Monospace: Source Code Pro (código)','  Display:   decorativas (títulos)','HIERARQUIA:','  H1: 32–48px bold → título principal','  H2: 24–32px medium → subtítulo','  Body: 16–18px regular → leitura','REGRA: máx. 2 fontes por projeto'], guia: null, tempos: [] },
  { sem: 4, tri: 1, tema: 'UI vs UX: diferenças, jornada do usuário e boas práticas', tipo: 'teoria', comp: 'Diferenciar UI e UX e compreender o papel de cada na criação de produtos digitais', hab: 'Mapear a jornada do usuário e identificar pontos de fricção em uma interface', aval: 'Jornada do usuário para um app fictício (AQL — produção textual)', rec: 'Projetor, post-its ou template digital, Miro/FigJam', quadro: ['UI vs UX — SEM. 4','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','UX — User Experience','  Como o usuário SE SENTE ao usar','  Pesquisa | Arquitetura | Fluxo',' ','UI — User Interface','  Como a interface PARECE e FUNCIONA','  Cores | Tipografia | Componentes',' ','JORNADA DO USUÁRIO:','  Descoberta → Onboarding → Uso','  → Retenção → Indicação'], guia: null, tempos: [] },
  { sem: 5, tri: 1, tema: 'Wireframes: criação de protótipos de baixa fidelidade no Figma', tipo: 'pratica', comp: 'Criar protótipos de baixa fidelidade para validar estruturas de páginas', hab: 'Usar o Figma para criar wireframes de telas web com componentes básicos', aval: 'Wireframe de 3 telas de um site (home, sobre, contato) (AQL — produção)', rec: 'Laboratório, Figma (figma.com), conta gratuita', quadro: ['WIREFRAMES — SEM. 5','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','WIREFRAME = esqueleto da interface','  Sem cores definitivas','  Sem imagens reais (só placeholders)','  Foco: estrutura e hierarquia',' ','FIGMA — ATALHOS BÁSICOS:','  R → retângulo | T → texto','  F → frame | Ctrl+D → duplicar','  Auto Layout: Shift+A',' ','COMPONENTES: nav, hero, cards, footer'], guia: null, tempos: [] },
  { sem: 6, tri: 1, tema: 'Prototipação no Figma: links entre telas, hover e fluxo de navegação', tipo: 'pratica', comp: 'Conectar telas em protótipos navegáveis no Figma', hab: 'Criar protótipos clicáveis com transições e fluxo de usuário no Figma', aval: 'Protótipo clicável com 3 telas navegáveis (AQL — produção)', rec: 'Laboratório, Figma', quadro: ['PROTOTIPAÇÃO — SEM. 6','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','FIGMA — MODO PROTOTYPE:','  Aba Prototype (painel direito)','  Arraste: componente → tela destino','  Trigger: On Click | On Hover','  Animation: Instant | Dissolve | Slide',' ','FLUXO:','  Home → Sobre → Contato → Home',' ','Compartilhar: "Share prototype" → link'], guia: null, tempos: [] },
  { sem: 7, tri: 1, tema: 'Projeto 1 — identidade visual e wireframe de site completo', tipo: 'projeto', comp: 'Integrar princípios de design, cores, tipografia e wireframe em projeto real', hab: 'Criar identidade visual e protótipo de site com 4 telas navegáveis no Figma', aval: 'Projeto 1 entregue com rubrica AQL + AQT', rec: 'Laboratório, Figma', quadro: ['PROJETO 1 — IDENTIDADE + WIREFRAME','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ENTREGÁVEIS:','  1. Paleta de 5 cores justificada','  2. Tipografia: 2 fontes + hierarquia','  3. Logo ou logotipo (Figma)','  4. Wireframe: 4 telas navegáveis','     (Home | Sobre | Serviços | Contato)',' ','RUBRICA: Hierarquia|Cores|Tipografia','  Wireframe|Prototipação|Justificativa'], guia: null, tempos: [] },
  { sem: 8, tri: 1, tema: 'Introdução à acessibilidade web: o que é, por que importa e WCAG 2.1', tipo: 'teoria', comp: 'Compreender os fundamentos da acessibilidade web e as diretrizes WCAG 2.1', hab: 'Identificar os 4 princípios WCAG (POUR) e relacioná-los a deficiências reais', aval: 'Mapa mental com os 4 princípios WCAG e exemplos (AQL — participação)', rec: 'Projetor, lousa, vídeo de leitor de tela (YouTube), WCAG 2.1 resumo', quadro: ['ACESSIBILIDADE WEB — SEM. 8','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','WCAG 2.1 — 4 PRINCÍPIOS (POUR):','  P — Perceptível','       conteúdo visível e audível','  O — Operável','       navegável sem mouse','  U — Compreensível','       linguagem clara, sem surpresas','  R — Robusto','       funciona em qualidade tecnologias',' ','Nível A | AA | AAA','Meta legal: WCAG 2.1 AA (Lei 13.146/2015)'], guia: null, tempos: [] },
  { sem: 9, tri: 1, tema: 'Acessibilidade: contraste de cores, tamanho de fonte e estrutura semântica', tipo: 'pratica', comp: 'Implementar acessibilidade visual em interfaces web com HTML semântico', hab: 'Verificar contraste mínimo 4.5:1 e aplicar tags semânticas acessíveis', aval: 'Correção de página HTML com falhas de contraste e semântica (AQL)', rec: 'Laboratório, VS Code, contrast-ratio.com, axe DevTools', quadro: ['ACESSIBILIDADE VISUAL — SEM. 9','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTRASTE (WCAG 1.4.3):','  Texto normal: mín. 4.5:1','  Texto grande (18px+): mín. 3:1','  Verificar: contrast-ratio.com',' ','FONTE:','  Mínimo 16px para corpo de texto','  Não usar px fixo → use rem',' ','SEMÂNTICA: <header><nav><main>','  <article><section><footer>','  → Sem <div> genérico p/ estrutura'], guia: null, tempos: [] },
  { sem: 10, tri: 1, tema: 'Formulários acessíveis: labels, fieldset, mensagens de erro e ARIA básico', tipo: 'pratica', comp: 'Criar formulários HTML acessíveis com labels, dicas e mensagens de erro', hab: 'Associar labels a inputs, usar fieldset/legend e adicionar atributos ARIA básicos', aval: 'Formulário de cadastro acessível auditado com axe (AQL — produção)', rec: 'Laboratório, VS Code, axe DevTools (extensão Chrome)', quadro: ['FORMULÁRIOS ACESSÍVEIS — SEM. 10','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','<label for="email">E-mail</label>','<input id="email" type="email"','  aria-required="true"','  aria-describedby="email-erro">',' ','<span id="email-erro" role="alert">','  Campo obrigatório.','</span>',' ','<fieldset>','  <legend>Dados pessoais</legend>','  ...','</fieldset>'], guia: null, tempos: [] },
  { sem: 11, tri: 1, tema: 'AQL — seminário: apresentação do Projeto 1 e portfólio de design', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar e defender escolhas de design com argumentação visual', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CRITÉRIOS (IN SUPEN 4/2024):','  Produção Textual: 40%','    → Projeto 1 + portfólio Figma','  Oralidade: 30%','    → Apresentação e defesa oral','  Participação: 30%','    → Engajamento nas aulas',' ','NOTA MÍNIMA: 6,0 pontos'], guia: null, tempos: [] },
  { sem: 12, tri: 1, tema: 'AQT — Avaliação Específica: princípios de design e acessibilidade', tipo: 'aval', comp: 'AQT: avaliação quantitativa conforme IN SUPEN 4/2024', hab: 'Demonstrar domínio dos conteúdos do 1º trimestre', aval: 'AQT — 50% objetiva + 50% discursiva — escala 0 a 10', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','FORMATO (IN SUPEN 4/2024):','  50% Múltipla Escolha (5 questões)','  50% Discursiva (2 questões)',' ','CONTEÚDO:','  Princípios C.R.A.P. e hierarquia','  Teoria das cores e tipografia','  UI vs UX | Wireframes (Figma)','  WCAG 2.1 — 4 princípios POUR','  Contraste | Semântica | Formulários'], guia: null, tempos: [] },
  { sem: 13, tri: 1, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'Recuperação Paralela Trimestral conforme SEDUC-PI', hab: 'Recuperar e consolidar aprendizagens do 1º trimestre', aval: 'RPT — nota substitui trimestral se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — RECUPERAÇÃO PARALELA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','A nota RPT SUBSTITUI a média','trimestral SE for ≥ 6,0',' ','ESTRATÉGIA:','→ Correção comentada da prova','→ Revisão princípios de design','→ Exercício: corrigir falhas de','  contraste e semântica em página HTML'], guia: null, tempos: [] },

  // ─── 2º TRIMESTRE ─────────────────────────────────────────
  { sem: 14, tri: 2, tema: 'Figma avançado: componentes, variantes e Auto Layout', tipo: 'pratica', comp: 'Criar sistemas de design reutilizáveis com componentes no Figma', hab: 'Criar componentes master, variantes de estado (default/hover/disabled) e Auto Layout', aval: 'Biblioteca de botões com 4 variantes no Figma (AQL — produção)', rec: 'Laboratório, Figma', quadro: ['FIGMA — COMPONENTES — SEM. 14','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','COMPONENTE MASTER:','  Ctrl+Alt+K → cria componente','  Instâncias: Ctrl+D (herdam estilo)',' ','VARIANTES:','  Add variant → Default | Hover','  Disabled | Error | Active',' ','AUTO LAYOUT (Shift+A):','  Direção: horizontal / vertical','  Gap entre filhos: 8px / 12px','  Padding: 12 16 (top/bottom, left/right)'], guia: null, tempos: [] },
  { sem: 15, tri: 2, tema: 'Design System: tokens de design, grid e biblioteca de componentes', tipo: 'teoria', comp: 'Compreender e estruturar um Design System com tokens e componentes', hab: 'Definir tokens de cor, tipografia e espaçamento e organizá-los em biblioteca Figma', aval: 'Design System básico (tokens + 5 componentes) (AQL — produção textual)', rec: 'Laboratório, Figma, referência Material Design / Tailwind', quadro: ['DESIGN SYSTEM — SEM. 15','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','TOKENS DE DESIGN:','  Cor:   primary-500 = #3B82F6','  Tipo:  font-size-lg = 18px','  Espaç: spacing-4 = 16px',' ','COMPONENTES BASE:','  Button | Input | Card | Badge | Modal',' ','GRID:','  12 colunas | Gutter 24px | Margin 40px',' ','Referências: Material Design, IBM Carbon'], guia: null, tempos: [] },
  { sem: 16, tri: 2, tema: 'Heurísticas de Nielsen: usabilidade e avaliação de interfaces', tipo: 'teoria', comp: 'Avaliar interfaces com as 10 heurísticas de usabilidade de Nielsen', hab: 'Identificar e documentar violações das heurísticas de Nielsen em sistemas reais', aval: 'Relatório de avaliação heurística de um site (AQL — produção textual)', rec: 'Laboratório, projetor, template de relatório heurístico', quadro: ['HEURÍSTICAS DE NIELSEN — SEM. 16','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','10 HEURÍSTICAS (top 5):','  1. Visibilidade do status do sistema','  2. Compatível com o mundo real','  3. Controle e liberdade do usuário','  4. Consistência e padrões','  5. Prevenção de erros',' ','SEVERIDADE: 0 → não é problema','  1 cosmético | 2 menor | 3 maior','  4 catastrófico (deve ser corrigido)'], guia: null, tempos: [] },
  { sem: 17, tri: 2, tema: 'Acessibilidade avançada: ARIA roles, labels e live regions', tipo: 'pratica', comp: 'Implementar ARIA para tornar componentes dinâmicos acessíveis', hab: 'Aplicar role, aria-label, aria-labelledby e aria-live em componentes interativos', aval: 'Modal e alerta acessíveis com ARIA implementados (AQL — produção)', rec: 'Laboratório, VS Code, NVDA (leitor de tela gratuito), Chrome DevTools', quadro: ['ARIA — SEM. 17','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ROLES: role="dialog|alert|navigation"','          role="button|checkbox|tab"',' ','LABELS:','  aria-label="Fechar modal"','  aria-labelledby="id-do-titulo"','  aria-describedby="id-da-desc"',' ','LIVE REGIONS:','  aria-live="polite"   → não urgente','  aria-live="assertive" → urgente (erro)',' ','REGRA: use HTML nativo antes de ARIA'], guia: null, tempos: [] },
  { sem: 18, tri: 2, tema: 'Navegação por teclado: focus, tabindex e skip links', tipo: 'pratica', comp: 'Garantir navegação completa por teclado em interfaces web', hab: 'Implementar skip link, ordem de foco lógica e estilos de foco visíveis', aval: 'Página navegável 100% por teclado verificada manualmente (AQL)', rec: 'Laboratório, VS Code, somente teclado para teste', quadro: ['NAVEGAÇÃO POR TECLADO — SEM. 18','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','SKIP LINK (WCAG 2.4.1):','<a href="#main" class="skip-link">','  Ir para o conteúdo principal</a>',' ','FOCUS:','  :focus-visible { outline: 3px solid #005FCC }','  NUNCA: outline: none (sem substituto)',' ','TABINDEX:','  0  → ordem natural do DOM','  -1 → remove do fluxo (foco via JS)','  >0 → evitar (quebra ordem natural)'], guia: null, tempos: [] },
  { sem: 19, tri: 2, tema: 'Leitores de tela: como funcionam e boas práticas para imagens e ícones', tipo: 'pratica', comp: 'Tornar conteúdo web acessível a usuários de leitores de tela', hab: 'Escrever textos alternativos eficientes e tornar ícones SVG acessíveis', aval: 'Página auditada com NVDA/VoiceOver — print do resultado (AQL)', rec: 'Laboratório, VS Code, NVDA (gratuito) ou VoiceOver (Mac/iOS)', quadro: ['LEITORES DE TELA — SEM. 19','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ALT TEXT (WCAG 1.1.1):','  Informativa: alt="Gráfico de barras..."','  Decorativa:  alt="" (vazio)','  Funcional:   alt="Pesquisar"',' ','ÍCONE SVG:','<svg aria-hidden="true"> (decorativo)','<svg role="img" aria-label="Fechar">',' ','RUIM: alt="imagem" | alt="foto1.jpg"','BOM:  Descreve a função ou o conteúdo'], guia: null, tempos: [] },
  { sem: 20, tri: 2, tema: 'Projeto 2 — redesign acessível de um site real', tipo: 'projeto', comp: 'Aplicar design acessível para melhorar uma interface existente com WCAG 2.1 AA', hab: 'Auditar, documentar problemas e criar redesign acessível no Figma', aval: 'Projeto 2 entregue com rubrica AQL + AQT', rec: 'Laboratório, Figma, axe DevTools, WAVE', quadro: ['PROJETO 2 — REDESIGN ACESSÍVEL','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ETAPAS:','  1. Escolher site com problemas reais','  2. Auditoria: listar violações WCAG','  3. Redesign no Figma (mín. 2 telas)','  4. Documentar melhorias aplicadas',' ','CRITÉRIOS:','  Contraste AA | Semântica | ARIA','  Foco visível | Alt text | Labels'], guia: null, tempos: [] },
  { sem: 21, tri: 2, tema: 'Acessibilidade cognitiva: linguagem simples, previsibilidade e erros', tipo: 'teoria', comp: 'Projetar interfaces compreensíveis para usuários com deficiências cognitivas', hab: 'Aplicar linguagem simples, consistência visual e mensagens de erro claras', aval: 'Reescrita de textos de interface complexos em linguagem simples (AQL)', rec: 'Projetor, lousa, exemplos de mensagens de erro boas e ruins', quadro: ['ACESSIBILIDADE COGNITIVA — SEM. 21','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','LINGUAGEM SIMPLES:','  Frases curtas (< 20 palavras)','  Voz ativa | Evite jargão técnico',' ','PREVISIBILIDADE (WCAG 3.2):','  Navegação consistente em todas as telas','  Ações previsíveis: confirmação antes','  de ações irreversíveis',' ','MENSAGENS DE ERRO:','  ✗ "Erro 404 — input inválido"','  ✓ "O e-mail deve ter @. Ex: joao@email.com"'], guia: null, tempos: [] },
  { sem: 22, tri: 2, tema: 'Dark mode, preferências de sistema e motion reduzido (CSS)', tipo: 'pratica', comp: 'Implementar dark mode e respeitar preferências de acessibilidade do sistema', hab: 'Usar prefers-color-scheme e prefers-reduced-motion em CSS', aval: 'Site com dark mode e animação removida quando solicitado (AQL)', rec: 'Laboratório, VS Code, DevTools (emular preferências)', quadro: ['PREFERÊNCIAS DO SISTEMA — SEM. 22','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','DARK MODE:','@media (prefers-color-scheme: dark) {','  body { background: #1a1a2e;','         color: #e2e4ea; }','}',' ','MOTION REDUZIDO:','@media (prefers-reduced-motion: reduce) {','  * { animation: none !important;','      transition: none !important; }','}',' ','DevTools → Rendering → Emulate...'], guia: null, tempos: [] },
  { sem: 23, tri: 2, tema: 'Ferramentas de auditoria: axe DevTools, Lighthouse e WAVE', tipo: 'pratica', comp: 'Auditar páginas web com ferramentas automatizadas de acessibilidade', hab: 'Executar auditorias com axe e Lighthouse e interpretar os relatórios gerados', aval: 'Relatório de auditoria axe + Lighthouse de uma página real (AQL)', rec: 'Laboratório, Chrome, extensão axe DevTools, Lighthouse (built-in)', quadro: ['FERRAMENTAS DE AUDITORIA — SEM. 23','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','axe DevTools (extensão Chrome):','  F12 → aba axe → Scan ALL','  Exibe: crítico | sério | moderado',' ','Lighthouse (F12 → Lighthouse):','  → Accessibility score 0–100','  → Lista problemas com links WCAG',' ','WAVE (wave.webaim.org):','  Cole a URL → análise visual inline',' ','ATENÇÃO: automação detecta ~30% dos erros','→ Teste manual sempre necessário'], guia: null, tempos: [] },
  { sem: 24, tri: 2, tema: 'Multimídia acessível: legendas, audiodescrição e transcrições', tipo: 'teoria', comp: 'Tornar conteúdo de áudio e vídeo acessível conforme WCAG 1.2', hab: 'Adicionar legendas em vídeo HTML5, criar transcrições e atribuir audiodescrição', aval: 'Vídeo com <track> de legendas WebVTT implementado (AQL)', rec: 'Laboratório, VS Code, arquivo .vtt exemplo, YouTube Studio', quadro: ['MULTIMÍDIA ACESSÍVEL — SEM. 24','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','LEGENDAS (WCAG 1.2.2):','<video controls>','  <source src="video.mp4">','  <track kind="captions"','    src="legendas.vtt"','    srclang="pt" label="Português">','</video>',' ','ARQUIVO VTT:','WEBVTT','00:00:01.000 --> 00:00:04.000','Olá, seja bem-vindo ao tutorial.'], guia: null, tempos: [] },
  { sem: 25, tri: 2, tema: 'AQL — apresentação do Projeto 2', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar redesign acessível com justificativa técnica das melhorias', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','APRESENTAÇÃO DO PROJETO 2','  Produção Textual (40%):','    → Figma + relatório de auditoria','  Oralidade (30%):','    → Demo ao vivo + perguntas','  Participação (30%):','    → Engajamento no trimestre',' ','TEMPO: 8–10 min por grupo/aluno'], guia: null, tempos: [] },
  { sem: 26, tri: 2, tema: 'AQT — Avaliação Específica: Figma, ARIA e auditoria', tipo: 'aval', comp: 'AQT: avaliação quantitativa do 2º trimestre', hab: 'Demonstrar domínio de componentes Figma, ARIA, teclado e ferramentas de auditoria', aval: '50% múltipla escolha + 50% discursiva', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  Figma: componentes, variantes','  Design System e tokens','  Heurísticas de Nielsen','  ARIA: roles, labels, live regions','  Navegação por teclado e foco','  Ferramentas: axe, Lighthouse, WAVE'], guia: null, tempos: [] },
  { sem: 27, tri: 2, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'RPT do 2º trimestre', hab: 'Consolidar aprendizagens do 2º trimestre', aval: 'RPT substitui nota se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PONTOS CRÍTICOS:','→ Componentes e variantes no Figma','→ Atributos ARIA e quando usar','→ Navegação por teclado (tabindex)','→ Diferença axe vs Lighthouse',' ','ESTRATÉGIA:','→ Correção comentada','→ Exercício prático: corrigir ARIA'], guia: null, tempos: [] },

  // ─── 3º TRIMESTRE ─────────────────────────────────────────
  { sem: 28, tri: 3, tema: 'Design inclusivo: personas com deficiência e cenários de uso', tipo: 'teoria', comp: 'Incorporar a perspectiva de usuários com deficiência no processo de design', hab: 'Criar personas que representem deficiências visuais, motoras e cognitivas', aval: 'Conjunto de 3 personas inclusivas com cenários de uso (AQL — produção)', rec: 'Laboratório, Figma ou template Word, vídeos de usuários com deficiência', quadro: ['DESIGN INCLUSIVO — SEM. 28','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PERSONA INCLUSIVA:','  Nome | Deficiência | Tecnologia usada','  Objetivo | Frustrações | Necessidades',' ','TIPOS:','  Visual: cegueira | baixa visão','  Motora: tremor | paralisia parcial','  Auditiva: surdez | perda parcial','  Cognitiva: dislexia | TDAH',' ','"Projete para o extremo, funciona','  para o meio." — Kat Holmes'], guia: null, tempos: [] },
  { sem: 29, tri: 3, tema: 'Design para dispositivos móveis: touch targets, gestos e acessibilidade', tipo: 'pratica', comp: 'Projetar interfaces móveis que respeitem padrões de acessibilidade em toque', hab: 'Dimensionar touch targets (mín. 44x44px) e criar gestos alternativos acessíveis', aval: 'Telas mobile no Figma com touch targets corretos verificados (AQL)', rec: 'Laboratório, Figma (frame iPhone 14), regra touch target', quadro: ['DESIGN MOBILE ACESSÍVEL — SEM. 29','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','TOUCH TARGET (WCAG 2.5.5):','  Mínimo: 44 × 44 px','  Recomendado: 48 × 48 px','  Espaçamento entre alvos: ≥ 8px',' ','GESTOS ACESSÍVEIS:','  Toda função por gesto → alternativa tap','  Swipe → botão alternativo visível',' ','THUMB ZONE:','  Área fácil (polegar): centro-baixo','  Área difícil: cantos superiores'], guia: null, tempos: [] },
  { sem: 30, tri: 3, tema: 'CSS avançado para acessibilidade: focus styles, skip link e modo alto contraste', tipo: 'pratica', comp: 'Implementar estilos CSS que melhoram acessibilidade visual e de navegação', hab: 'Criar skip link funcional, :focus-visible personalizado e suporte a alto contraste', aval: 'Página com skip link, foco customizado e alto contraste funcionando (AQL)', rec: 'Laboratório, VS Code, Chrome DevTools', quadro: ['CSS ACESSÍVEL — SEM. 30','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','SKIP LINK:','.skip-link { position:absolute; top:-40px }','.skip-link:focus { top:0 }',' ','FOCO VISÍVEL:',':focus-visible {','  outline: 3px solid #005FCC;','  outline-offset: 3px;','}',' ','ALTO CONTRASTE:','@media (forced-colors: active) {','  .btn { border: 2px solid ButtonText }','}'], guia: null, tempos: [] },
  { sem: 31, tri: 3, tema: 'Imagens acessíveis: alt text eficiente, SVG e figuras com legenda', tipo: 'pratica', comp: 'Tornar todo conteúdo visual acessível com descrições e marcações corretas', hab: 'Escrever alt text contextualizado, tratar SVG com título e usar figure/figcaption', aval: 'Galeria de imagens com alt texts e SVGs acessíveis auditada com axe (AQL)', rec: 'Laboratório, VS Code, axe DevTools', quadro: ['IMAGENS ACESSÍVEIS — SEM. 31','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ALT TEXT:','  Informativa: "Gráfico de barras","  mostrando crescimento de 40%"','  Decorativa: alt=""',' ','FIGURE:','<figure>','  <img src="foto.jpg" alt="...">','  <figcaption>Fonte: IBGE 2023</figcaption>','</figure>',' ','SVG ACESSÍVEL:','<svg role="img" aria-labelledby="titulo">','  <title id="titulo">Ícone de busca</title>','{...}','</svg>'], guia: null, tempos: [] },
  { sem: 32, tri: 3, tema: 'Tabelas acessíveis: scope, caption e headers complexos', tipo: 'pratica', comp: 'Estruturar tabelas de dados acessíveis para leitores de tela', hab: 'Usar caption, scope, headers e summary para tornar tabelas compreensíveis', aval: 'Tabela de notas ou dados acessível auditada com NVDA (AQL)', rec: 'Laboratório, VS Code, NVDA', quadro: ['TABELAS ACESSÍVEIS — SEM. 32','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','<table>','  <caption>Notas do 1º Trimestre</caption>','  <thead>','    <tr>','      <th scope="col">Aluno</th>','      <th scope="col">Nota</th>','    </tr>','  </thead>','  <tbody>','    <tr>','      <td>Ana</td><td>8,5</td>','    </tr>','  </tbody>','</table>'], guia: null, tempos: [] },
  { sem: 33, tri: 3, tema: 'Auditoria completa WCAG 2.1 AA: checklist e relatório técnico', tipo: 'pratica', comp: 'Executar auditoria de acessibilidade completa em site real com checklist WCAG', hab: 'Combinar testes automatizados e manuais para gerar relatório WCAG 2.1 AA', aval: 'Relatório de auditoria completa com critérios de sucesso avaliados (AQL)', rec: 'Laboratório, Chrome, axe, NVDA, checklist WCAG 2.1 AA impresso', quadro: ['AUDITORIA WCAG 2.1 AA — SEM. 33','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METODOLOGIA:','  1. Scan automatizado (axe + Lighthouse)','  2. Teste manual por teclado','  3. Teste com leitor de tela (NVDA)','  4. Verificar contraste manualmente','  5. Verificar textos alternativos',' ','RELATÓRIO:','  Critério WCAG | Nível | Status','  Evidência | Recomendação'], guia: null, tempos: [] },
  { sem: 34, tri: 3, tema: 'Projeto Final — planejamento: briefing, persona, wireframe acessível', tipo: 'projeto', comp: 'Planejar projeto de design acessível com documentação completa', hab: 'Produzir briefing, personas inclusivas, wireframe e checklist WCAG do projeto', aval: 'Entrega do plano de projeto com wireframe acessível (AQL — produção textual)', rec: 'Laboratório, Figma, template de documentação', quadro: ['PROJETO FINAL — PLANEJAMENTO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','DOCUMENTAÇÃO MÍNIMA:','  1. Briefing: público-alvo e objetivos','  2. Personas inclusivas (2 mínimo)','  3. Wireframe: 4+ telas navegáveis','  4. Paleta de cores (contraste AA)','  5. Tipografia e tokens de design','  6. Checklist WCAG 2.1 AA do projeto'], guia: null, tempos: [] },
  { sem: 35, tri: 3, tema: 'Projeto Final — design de alta fidelidade no Figma', tipo: 'projeto', comp: 'Executar o design visual completo com componentes acessíveis', hab: 'Criar mockups de alta fidelidade com Design System e estados de componentes', aval: 'Checkpoint 1 — mockups de 4+ telas entregues', rec: 'Laboratório, Figma', quadro: ['PROJETO FINAL — CHECKPOINT 1','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 35:','→ Todas as telas em alta fidelidade','→ Componentes com variantes (hover/focus)','→ Contraste verificado em todas as cores','→ Tipografia com hierarquia clara','→ Ícones com alt ou aria-label definidos'], guia: null, tempos: [] },
  { sem: 36, tri: 3, tema: 'Projeto Final — implementação HTML/CSS acessível', tipo: 'projeto', comp: 'Codificar o projeto em HTML e CSS respeitando WCAG 2.1 AA', hab: 'Implementar as telas com semântica, ARIA, foco e contraste corretos', aval: 'Checkpoint 2 — páginas HTML com score axe ≥ 90 pontos', rec: 'Laboratório, VS Code, axe DevTools', quadro: ['PROJETO FINAL — CHECKPOINT 2','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 36:','→ HTML semântico em todas as telas','→ Formulários com label e ARIA','→ Skip link funcionando','→ Foco visível em todos os elementos','→ axe DevTools: 0 erros críticos','→ Navegação por teclado 100%'], guia: null, tempos: [] },
  { sem: 37, tri: 3, tema: 'Projeto Final — testes de acessibilidade, ajustes e documentação', tipo: 'projeto', comp: 'Finalizar, testar e documentar o projeto acessível completo', hab: 'Executar auditoria final e corrigir falhas antes da apresentação', aval: 'Sistema publicado + relatório de auditoria + documentação entregue', rec: 'Laboratório, VS Code, axe, NVDA, servidor de deploy', quadro: ['PROJETO FINAL — ENTREGA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ENTREGÁVEIS:','  1. Protótipo Figma (link público)','  2. Código HTML/CSS (GitHub ou .zip)','  3. Relatório de auditoria WCAG AA','  4. Documentação do Design System',' ','RUBRICA: Hierarquia|Contraste|Semântica','  ARIA|Teclado|Figma|Documentação'], guia: null, tempos: [] },
  { sem: 38, tri: 3, tema: 'AQL — banca avaliadora do Projeto Final', tipo: 'aval', comp: 'AQL final: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar projeto de design acessível com demo e justificativa técnica', aval: 'AQL final — nota mínima 6,0 — IN SUPEN 4/2024', rec: 'Projetor, ficha de avaliação da banca', quadro: ['AQL FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','BANCA AVALIADORA','  Produção Textual (40%):','    → Figma + código + relatório WCAG','  Oralidade (30%):','    → Demo ao vivo + perguntas técnicas','  Participação (30%):','    → Engajamento no trimestre',' ','DURAÇÃO: 10 min por grupo/aluno'], guia: null, tempos: [] },
  { sem: 39, tri: 3, tema: 'AQT — Avaliação Específica Final: design inclusivo e auditoria WCAG', tipo: 'aval', comp: 'AQT final: avaliação quantitativa do 3º trimestre', hab: 'Demonstrar domínio de design inclusivo, CSS acessível e auditoria WCAG completa', aval: '50% objetiva + 50% discursiva — escala 0 a 10', rec: 'Prova impressa, sala de aula', quadro: ['AQT FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  Design inclusivo e personas','  Mobile: touch targets e gestos','  CSS: skip link, :focus-visible','  Imagens e tabelas acessíveis','  Auditoria WCAG 2.1 AA completa',' ','5 objetivas (50%) + 2 discursivas (50%)'], guia: null, tempos: [] },
  { sem: 40, tri: 3, tema: 'Conselho de Classe, revisão anual e encerramento', tipo: 'aval', comp: 'Avaliação global e encerramento do ano letivo', hab: 'Refletir sobre o percurso e identificar aprendizagens', aval: 'Conselho de Classe — art. 17 Regimento SEDUC-PI', rec: 'Ficha do Conselho de Classe, diário de bordo', quadro: ['ENCERRAMENTO — SEM. 40','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONSELHO DE CLASSE:','→ Análise da turma (rendimento)','→ Alunos com nota < 6,0','→ Deliberação: aprovação / PF',' ','PROVA FINAL (PF):','→ Para alunos com MA < 6,0','→ Frequência mínima 75%'], guia: null, tempos: [] }
];
