// ============================================================
// SEQUÊNCIA DIDÁTICA — Programação Orientada a Objetos — 2º Ano
// 40 semanas letivas — 3 trimestres — SEDUC-PI PPC 2024
// Edite os temas, competências e conteúdos conforme necessário
// ============================================================

const AULAS_POO = [
  // ─── 1º TRIMESTRE ─────────────────────────────────────────
  {
    sem: 1, tri: 1,
    tema: 'Paradigmas de programação: procedural vs orientado a objetos',
    tipo: 'teoria',
    comp: 'Compreender os fundamentos e a história da Programação Orientada a Objetos',
    hab: 'Diferenciar paradigma procedural e orientado a objetos com exemplos práticos',
    aval: 'Mapa conceitual comparativo + debate em sala (AQL — participação)',
    rec: 'Projetor, lousa, slides, exemplos de código C e Java',
    quadro: [
      'POO — PARADIGMAS — SEM. 1',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'PROCEDURAL',
      '  Código = sequência de instruções',
      '  Dados e funções separados',
      '  Ex: linguagem C',
      ' ',
      'ORIENTADO A OBJETOS',
      '  Código = objetos que interagem',
      '  Dados + comportamentos juntos',
      '  Ex: Java | Python | C#',
      ' ',
      '4 PILARES: Encapsulamento | Herança',
      '          Polimorfismo | Abstração'
    ],
    guia: [
      { num: 1, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Abertura — o que é um objeto? (10 min)', desc: 'Pergunte: "Um carro tem características e ações — cite 3 de cada." Anote as respostas no quadro (cor, modelo, marca | acelerar, frear, ligar). Relate: "Em POO, essas características são atributos e essas ações são métodos." Não corrija — deixe os alunos construir o conceito.', dica: 'Objetos do cotidiano (celular, caderno, aluno) funcionam melhor que exemplos abstratos para iniciantes.', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Procedural vs OO — comparação no quadro (15 min)', desc: 'Escreva no quadro os dois paradigmas lado a lado. Mostre código procedural (em C ou pseudo-código) calculando a média de um aluno, depois mostre a mesma lógica em Java com uma classe Aluno. Destaque: "No OO, o aluno é responsável por calcular sua própria média."', dica: 'Não precisa que o código compile agora — o objetivo é a compreensão conceitual do paradigma.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#3C3489', bg: '#EEEDFE', titulo: 'Os 4 pilares da POO (15 min)', desc: 'Escreva os 4 pilares no quadro e dê uma analogia para cada: Encapsulamento = caixa-preta (você usa o controle remoto sem ver a eletrônica); Herança = filho herda características do pai; Polimorfismo = um botão "compartilhar" que funciona de formas diferentes; Abstração = você dirige sem saber como o motor funciona.', dica: 'Registre quem participa das analogias — compõe AQL participação 30%.', dicaBg: '#EEEDFE', dicaCor: '#26215C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Verificação da aprendizagem (10 min)', desc: 'Faça 4 perguntas rápidas, uma por pilar: "Um método privado que protege um dado — qual pilar?" | "Classe Cachorro herda de Animal — qual pilar?" | "Mesmo método, comportamentos diferentes — qual pilar?" | "Usar sem entender o interior — qual pilar?" Anote participação (AQL).', dica: 'AQL — Participação: registre os nomes de quem respondeu corretamente.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese e tarefa (10 min)', desc: 'Copie o esquema final no quadro. Peça que copiem no caderno. Síntese: "POO organiza o código em objetos que unem dados e comportamentos, tornando o sistema mais organizado e reutilizável." Tarefa: pesquisar uma linguagem OO e 2 exemplos de uso no mercado.', dica: '"Na próxima aula vocês já escrevem sua primeira classe Java." Gera expectativa positiva.', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Abertura', t: '10 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Paradigmas', t: '15 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: '4 Pilares', t: '15 min', bg: '#EEEDFE', c: '#3C3489' },
      { label: 'Verificação', t: '10 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '10 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  {
    sem: 2, tri: 1,
    tema: 'Classes e objetos: conceitos fundamentais e primeiro código Java',
    tipo: 'teoria',
    comp: 'Identificar e modelar classes e objetos a partir de problemas reais',
    hab: 'Declarar uma classe Java com atributos e métodos e instanciar objetos',
    aval: 'Classe Produto implementada com atributos e método exibir() (AQL — produção)',
    rec: 'Laboratório de informática, VS Code + extensão Java, JDK instalado',
    quadro: [
      'CLASSES E OBJETOS — SEM. 2',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'CLASSE = molde / planta',
      'OBJETO = instância da classe',
      ' ',
      'class Aluno {',
      '  String nome;',
      '  int matricula;',
      '  double nota;',
      ' ',
      '  void apresentar() {',
      '    System.out.println(nome);',
      '  }',
      '}',
      ' ',
      'Aluno a = new Aluno();',
      'a.nome = "Maria";',
      'a.apresentar();'
    ],
    guia: [
      { num: 1, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Retomada e lançamento (5 min)', desc: 'Retome a tarefa: 1-2 alunos apresentam a linguagem OO que pesquisaram. Registre participação. Anuncie: "Hoje vocês criam a primeira classe Java — um molde que gera objetos." Peça que abram VS Code.', dica: 'Registre quem trouxe a tarefa — participação AQL (30%).', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Analogia: molde e objeto (10 min)', desc: 'Use a analogia da forma de bolo: "A classe é a forma, os objetos são os bolos. Todos têm a mesma estrutura, mas com recheios diferentes." Desenhe no quadro: CLASSE Aluno → objeto Maria (nota 8,5) e objeto João (nota 7,0). Mostre que a classe define o que cada aluno TEM (atributos) e o que cada aluno FAZ (métodos).', dica: 'Outras boas analogias: certidão de nascimento (classe) vs pessoa (objeto); projeto arquitetônico vs casa.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#3C3489', bg: '#EEEDFE', titulo: 'Demonstração no projetor — primeira classe Java (15 min)', desc: 'Crie Aluno.java no VS Code ao vivo. Declare a classe, adicione atributos (String nome, int matricula, double nota) e o método apresentar(). Depois crie Main.java, instancie dois objetos Aluno, atribua valores e chame o método. Compile e execute no terminal.', dica: 'Mostre o terminal rodando — ver o output "Maria" impresso é muito motivador para iniciantes.', dicaBg: '#EEEDFE', dicaCor: '#26215C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Prática guiada — classe Produto (25 min)', desc: 'Passe o desafio: criar a classe Produto com atributos String nome, double preco, int estoque e método void exibir() que imprime os dados. Em Main, instanciar 2 produtos e chamar exibir(). Circule pela sala. Anote quem entrega funcionando (AQL — produção 40%).', dica: 'Erro "cannot find symbol" = nome do atributo digitado errado. Ensine a ler o erro antes de ajudar.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese (5 min)', desc: 'Mostre 1 solução no projetor. Elogie o esforço. Síntese: "Classe = estrutura. Objeto = instância com valores próprios. new cria o objeto na memória." Conecte à próxima aula: "Na semana 3 vamos controlar quem pode ou não acessar os atributos — isso é encapsulamento."', dica: '"Quem fez funcionar hoje já programa orientado a objetos. Isso está no currículo de faculdade de TI."', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Retomada', t: '5 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Analogia', t: '10 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: 'Demo Java', t: '15 min', bg: '#EEEDFE', c: '#3C3489' },
      { label: 'Prática', t: '25 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '5 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  { sem: 3, tri: 1, tema: 'Encapsulamento: private, public, protected, getters e setters', tipo: 'pratica', comp: 'Aplicar encapsulamento para proteger dados de uma classe', hab: 'Declarar atributos privados e criar métodos getters e setters em Java', aval: 'Refatorar classe Aluno com encapsulamento completo (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['ENCAPSULAMENTO — SEM. 3','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class ContaBancaria {','  private double saldo;','  private String titular;',' ','  public double getSaldo() {','    return saldo;','  }','  public void setSaldo(double v) {','    if (v >= 0) saldo = v;','  }','}',' ','REGRA: atributo private','  acesso via get/set public'], guia: null, tempos: [] },
  { sem: 4, tri: 1, tema: 'Construtores: padrão, parametrizado e sobrecarga de construtores', tipo: 'pratica', comp: 'Inicializar objetos de forma controlada com construtores', hab: 'Criar construtores parametrizados e sobrecarregar construtores em Java', aval: 'Classe com 2 construtores funcionando (AQL — produção)', rec: 'Laboratório, VS Code, JDK', quadro: ['CONSTRUTORES — SEM. 4','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Aluno {','  private String nome;','  private double nota;',' ','  // Construtor padrão','  public Aluno() { nota = 0.0; }',' ','  // Construtor parametrizado','  public Aluno(String n, double nt) {','    nome = n; nota = nt;','  }','}',' ','Aluno a1 = new Aluno();','Aluno a2 = new Aluno("Ana", 8.5);'], guia: null, tempos: [] },
  { sem: 5, tri: 1, tema: 'Palavra-chave this, atributos e métodos estáticos (static)', tipo: 'pratica', comp: 'Distinguir contexto de instância e contexto de classe', hab: 'Usar this para referenciar o objeto atual e static para membros de classe', aval: 'Classe com contador estático de objetos criados (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['this E static — SEM. 5','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Aluno {','  private String nome;','  private static int contador = 0;',' ','  public Aluno(String nome) {','    this.nome = nome; // this = este objeto','    contador++;       // static = da classe','  }',' ','  public static int getContador() {','    return contador;','  }','}',' ','System.out.println(Aluno.getContador());'], guia: null, tempos: [] },
  { sem: 6, tri: 1, tema: 'Arrays de objetos e ArrayList — coleções de instâncias', tipo: 'pratica', comp: 'Armazenar e manipular múltiplos objetos em coleções', hab: 'Usar arrays e ArrayList para gerenciar listas de objetos em Java', aval: 'Lista de 5 produtos cadastrados e exibidos (AQL — produção)', rec: 'Laboratório, VS Code, JDK', quadro: ['ARRAYS E ARRAYLIST — SEM. 6','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','// Array de objetos','Aluno[] turma = new Aluno[30];','turma[0] = new Aluno("Ana", 8.5);',' ','// ArrayList (dinâmico)','import java.util.ArrayList;','ArrayList<Aluno> lista = new ArrayList<>();','lista.add(new Aluno("João", 7.0));','lista.add(new Aluno("Maria", 9.0));',' ','for (Aluno a : lista) {','  a.apresentar();','}'], guia: null, tempos: [] },
  { sem: 7, tri: 1, tema: 'Projeto 1 — sistema de cadastro com classes e encapsulamento', tipo: 'projeto', comp: 'Integrar classes, encapsulamento e coleções em um sistema funcional', hab: 'Construir um sistema de cadastro completo com ArrayList e menu no terminal', aval: 'Projeto 1 entregue com rubrica AQL + AQT', rec: 'Laboratório, VS Code, JDK', quadro: ['PROJETO 1 — CADASTRO POO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','REQUISITOS MÍNIMOS:','  1. Classe com encapsulamento','  2. Construtores parametrizados','  3. ArrayList de objetos','  4. Menu: cadastrar/listar/buscar','  5. Validação nos setters',' ','RUBRICA:','  Encapsulamento|Construtor','  ArrayList|Menu|Código limpo'], guia: null, tempos: [] },
  { sem: 8, tri: 1, tema: 'UML — diagrama de classes: notação, atributos, métodos e relacionamentos', tipo: 'teoria', comp: 'Representar visualmente sistemas orientados a objetos com UML', hab: 'Desenhar diagramas de classes com atributos, métodos e visibilidade', aval: 'Diagrama UML de 3 classes relacionadas (AQL — produção textual)', rec: 'Projetor, papel quadriculado, draw.io (opcional)', quadro: ['UML — DIAGRAMA DE CLASSES','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','┌──────────────────┐','│    Aluno         │','├──────────────────┤','│ -nome: String    │','│ -nota: double    │','├──────────────────┤','│ +getNome(): String│','│ +calcMedia(): double│','└──────────────────┘',' ','VISIBILIDADE:','  + público  - privado  # protegido'], guia: null, tempos: [] },
  { sem: 9, tri: 1, tema: 'Abstração e modelagem OO: identificar classes em problemas reais', tipo: 'pratica', comp: 'Modelar sistemas orientados a objetos a partir de requisitos', hab: 'Identificar classes, atributos e métodos em um problema descrito em português', aval: 'Modelagem de um sistema de biblioteca ou estoque (AQL)', rec: 'Laboratório, papel/quadro, draw.io', quadro: ['ABSTRAÇÃO — MODELAGEM OO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PASSOS:','1. Leia o problema','2. Sublinhe os substantivos → classes','3. Sublinhe os adjetivos → atributos','4. Sublinhe os verbos → métodos',' ','EXEMPLO — Sistema de Biblioteca:','  Livro: titulo, autor, isbn, disponivel','  Leitor: nome, cpf, telefone','  Emprestimo: livro, leitor, dataDevol.'], guia: null, tempos: [] },
  { sem: 10, tri: 1, tema: 'Boas práticas em POO: nomenclatura, coesão e responsabilidade única', tipo: 'teoria', comp: 'Escrever código orientado a objetos limpo e coeso', hab: 'Aplicar convenções Java e o princípio de responsabilidade única (SRP)', aval: 'Refatoração de código com má prática (AQL — participação)', rec: 'Laboratório, VS Code, exemplos de código ruim e bom', quadro: ['BOAS PRÁTICAS — SEM. 10','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','NOMENCLATURA JAVA:','  Classe: PascalCase   → ContaBancaria','  Método: camelCase    → calcularSaldo()','  Constante: UPPER     → TAXA_JUROS',' ','COESÃO: cada classe = 1 responsabilidade','  ✗ Aluno que também salva no banco','  ✓ Aluno (dados) + AlunoDAO (banco)',' ','"Clean Code" — Robert C. Martin'], guia: null, tempos: [] },
  { sem: 11, tri: 1, tema: 'AQL — seminário: apresentação do Projeto 1 e portfólio', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar e defender o Projeto 1 com argumentação técnica', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CRITÉRIOS (IN SUPEN 4/2024):','  Produção Textual: 40%','    → Projeto 1 + documentação','  Oralidade: 30%','    → Apresentação e defesa oral','  Participação: 30%','    → Engajamento nas aulas',' ','NOTA MÍNIMA: 6,0 pontos'], guia: null, tempos: [] },
  { sem: 12, tri: 1, tema: 'AQT — Avaliação Específica: paradigmas, classes e encapsulamento', tipo: 'aval', comp: 'AQT: avaliação quantitativa conforme IN SUPEN 4/2024', hab: 'Demonstrar domínio dos conteúdos do 1º trimestre', aval: 'AQT — 50% objetiva + 50% discursiva — escala 0 a 10', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','FORMATO (IN SUPEN 4/2024):','  50% Múltipla Escolha (5 questões)','  50% Discursiva (2 questões)',' ','CONTEÚDO:','  Paradigmas e pilares POO','  Classes, objetos, atributos, métodos','  Encapsulamento (private/get/set)','  Construtores e static','  ArrayList de objetos'], guia: null, tempos: [] },
  { sem: 13, tri: 1, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'Recuperação Paralela Trimestral conforme SEDUC-PI', hab: 'Recuperar e consolidar aprendizagens do 1º trimestre', aval: 'RPT — nota substitui trimestral se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — RECUPERAÇÃO PARALELA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','A nota RPT SUBSTITUI a média','trimestral SE for ≥ 6,0',' ','ESTRATÉGIA:','→ Correção comentada da prova','→ Revisão dos pontos críticos','→ Exercício de reforço: classe completa','  com encapsulamento e ArrayList'], guia: null, tempos: [] },

  // ─── 2º TRIMESTRE ─────────────────────────────────────────
  { sem: 14, tri: 2, tema: 'Herança: extends, super(), hierarquia e reaproveitamento de código', tipo: 'teoria', comp: 'Aplicar herança para reutilizar e estender classes', hab: 'Criar subclasses com extends, chamar o construtor pai com super()', aval: 'Hierarquia Pessoa → Aluno → Professor implementada (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['HERANÇA — SEM. 14','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Pessoa {','  protected String nome;','  protected String cpf;','  public Pessoa(String n, String c) {','    nome = n; cpf = c;','  }','}',' ','class Aluno extends Pessoa {','  private String matricula;','  public Aluno(String n, String c, String m) {','    super(n, c);  // chama Pessoa()','    matricula = m;','  }','}'], guia: null, tempos: [] },
  { sem: 15, tri: 2, tema: 'Sobrescrita de métodos: @Override, regras e uso correto', tipo: 'pratica', comp: 'Redefinir comportamentos herdados com sobrescrita de métodos', hab: 'Usar @Override para especializar métodos em subclasses Java', aval: 'Método toString() sobrescrito em 3 subclasses (AQL — produção)', rec: 'Laboratório, VS Code, JDK', quadro: ['@OVERRIDE — SEM. 15','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Animal {','  public String emitirSom() {','    return "Som genérico";','  }','}',' ','class Cachorro extends Animal {','  @Override','  public String emitirSom() {','    return "Au au!";','  }','}',' ','REGRA: mesma assinatura, novo comportamento','toString() | equals() | hashCode()'], guia: null, tempos: [] },
  { sem: 16, tri: 2, tema: 'Polimorfismo: upcasting, downcasting e operador instanceof', tipo: 'pratica', comp: 'Explorar polimorfismo para flexibilizar sistemas orientados a objetos', hab: 'Aplicar upcasting e downcasting e verificar tipos com instanceof', aval: 'Sistema com lista polimórfica de Funcionários (AQL — produção)', rec: 'Laboratório, VS Code, JDK', quadro: ['POLIMORFISMO — SEM. 16','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','// Upcasting — subclasse → superclasse','Animal a = new Cachorro();','a.emitirSom();  // "Au au!" (sobrescrito)',' ','// Lista polimórfica','ArrayList<Animal> animais = new ArrayList<>();','animais.add(new Cachorro());','animais.add(new Gato());','for (Animal x : animais) x.emitirSom();',' ','// instanceof','if (a instanceof Cachorro) { ... }'], guia: null, tempos: [] },
  { sem: 17, tri: 2, tema: 'Classes abstratas: abstract class e métodos abstratos', tipo: 'teoria', comp: 'Usar classes abstratas para definir contratos parciais de comportamento', hab: 'Declarar classes e métodos abstratos e forçar implementação em subclasses', aval: 'Hierarquia com classe abstrata Forma geométrica (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['CLASSE ABSTRATA — SEM. 17','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','abstract class Forma {','  protected String cor;',' ','  // Método abstrato — sem corpo','  public abstract double calcularArea();',' ','  // Método concreto','  public void exibir() {','    System.out.println("Forma: " + cor);','  }','}',' ','class Circulo extends Forma {','  @Override','  public double calcularArea() {','    return Math.PI * raio * raio;','  }','}'], guia: null, tempos: [] },
  { sem: 18, tri: 2, tema: 'Interfaces: interface, implements e contratos de comportamento', tipo: 'pratica', comp: 'Definir contratos de comportamento com interfaces Java', hab: 'Criar interfaces e implementá-las em múltiplas classes independentes', aval: 'Interface Pagavel implementada por Boleto e CartaoCredito (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['INTERFACES — SEM. 18','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','interface Pagavel {','  void processar();','  double getValor();','}',' ','class Boleto implements Pagavel {','  @Override','  public void processar() {','    System.out.println("Gerando boleto...");','  }','}',' ','DIFERENÇA:','  Abstrata: herança parcial + herança normal','  Interface: contrato puro (múltiplos)'], guia: null, tempos: [] },
  { sem: 19, tri: 2, tema: 'Associação, agregação e composição entre classes', tipo: 'pratica', comp: 'Modelar relacionamentos entre classes com associação, agregação e composição', hab: 'Implementar os três tipos de relacionamento em Java com UML correspondente', aval: 'Sistema com composição Pedido → ItemPedido (AQL — produção)', rec: 'Laboratório, VS Code, JDK, draw.io', quadro: ['RELACIONAMENTOS — SEM. 19','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ASSOCIAÇÃO: usa um objeto do outro','  Aluno usa Biblioteca (fraca)','  Aluno alunoAtual; → pode ser null',' ','AGREGAÇÃO: tem, mas sobrevive sem','  Turma tem Alunos','  ArrayList<Aluno> alunos;',' ','COMPOSIÇÃO: tem e depende (nasce/morre junto)','  Pedido tem ItensPedido','  itens criados dentro do Pedido'], guia: null, tempos: [] },
  { sem: 20, tri: 2, tema: 'Projeto 2 — sistema com herança, polimorfismo e interfaces', tipo: 'projeto', comp: 'Integrar herança, polimorfismo e interfaces em sistema funcional', hab: 'Construir hierarquia de classes com lista polimórfica e interface', aval: 'Projeto 2 entregue com rubrica AQL + AQT', rec: 'Laboratório, VS Code, JDK', quadro: ['PROJETO 2 — HERANÇA E POO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','REQUISITOS MÍNIMOS:','  1. Superclasse abstrata','  2. Mín. 2 subclasses concretas','  3. @Override em métodos-chave','  4. Interface com 1+ método','  5. Lista polimórfica (ArrayList<Super>)','  6. Diagrama UML do sistema',' ','Sugestões: sistema de funcionários,','  loja de produtos, banco, escola'], guia: null, tempos: [] },
  { sem: 21, tri: 2, tema: 'Tratamento de exceções: try, catch, finally e throws', tipo: 'pratica', comp: 'Escrever código robusto com tratamento de exceções em Java', hab: 'Usar try/catch/finally e propagar exceções com throws', aval: 'Método com tratamento de exceção e mensagem de erro (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['EXCEÇÕES — SEM. 21','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','try {','  int resultado = a / b;','} catch (ArithmeticException e) {','  System.out.println("Erro: " + e.getMessage());','} finally {','  System.out.println("Executado sempre");','}',' ','throws na assinatura:','  public void abrir() throws IOException',' ','HIERARQUIA: Throwable → Exception → RuntimeException'], guia: null, tempos: [] },
  { sem: 22, tri: 2, tema: 'Exceções personalizadas e validação de dados', tipo: 'pratica', comp: 'Criar e lançar exceções customizadas para validação de negócio', hab: 'Estender Exception para criar exceções específicas do domínio', aval: 'Classe com exceção personalizada SaldoInsuficienteException (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['EXCEÇÃO PERSONALIZADA — SEM. 22','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class SaldoInsuficienteException','  extends Exception {',' ','  public SaldoInsuficienteException(double v) {','    super("Saldo insuficiente. Faltam R$" + v);','  }','}',' ','public void sacar(double v)','  throws SaldoInsuficienteException {','  if (v > saldo)','    throw new SaldoInsuficienteException(v - saldo);','  saldo -= v;','}'], guia: null, tempos: [] },
  { sem: 23, tri: 2, tema: 'Coleções Java: ArrayList, HashMap e HashSet na prática', tipo: 'pratica', comp: 'Gerenciar conjuntos de dados com as principais coleções Java', hab: 'Escolher e usar a coleção adequada para cada problema', aval: 'Programa com ArrayList + HashMap funcionando (AQL — produção)', rec: 'Laboratório, VS Code, JDK', quadro: ['COLEÇÕES — SEM. 23','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ArrayList<String> nomes = new ArrayList<>();','nomes.add("Ana"); nomes.remove(0);',' ','HashMap<String,Integer> notas = new HashMap<>();','notas.put("Ana", 9);','notas.get("Ana"); // → 9',' ','HashSet<String> cpfs = new HashSet<>();','cpfs.add("123.456"); // sem duplicatas',' ','QUANDO USAR:','  Lista ordenada → ArrayList','  Chave-valor       → HashMap','  Sem duplicata     → HashSet'], guia: null, tempos: [] },
  { sem: 24, tri: 2, tema: 'Lambda, Streams e Comparable — ordenação e filtragem de coleções', tipo: 'pratica', comp: 'Processar coleções de forma funcional com lambda e Streams', hab: 'Usar Comparator, sort(), stream().filter() e stream().map() em Java', aval: 'Lista de objetos ordenada e filtrada com lambda (AQL)', rec: 'Laboratório, VS Code, JDK 8+', quadro: ['LAMBDA E STREAMS — SEM. 24','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','// Ordenar por nota','lista.sort((a, b) ->','  Double.compare(a.getNota(), b.getNota()));',' ','// Filtrar aprovados','lista.stream()','  .filter(a -> a.getNota() >= 6.0)','  .forEach(a -> System.out.println(a.getNome()));',' ','// Map — transformar','lista.stream().map(Aluno::getNome)','  .collect(Collectors.toList());'], guia: null, tempos: [] },
  { sem: 25, tri: 2, tema: 'AQL — apresentação do Projeto 2', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar sistema com herança e polimorfismo com argumentação técnica', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','APRESENTAÇÃO DO PROJETO 2','  Produção Textual (40%):','    → Código + diagrama UML','  Oralidade (30%):','    → Demo ao vivo + perguntas','  Participação (30%):','    → Engajamento no trimestre',' ','TEMPO: 8–10 min por grupo/aluno'], guia: null, tempos: [] },
  { sem: 26, tri: 2, tema: 'AQT — Avaliação Específica: herança, polimorfismo e exceções', tipo: 'aval', comp: 'AQT: avaliação quantitativa do 2º trimestre', hab: 'Demonstrar domínio de herança, interfaces, polimorfismo e coleções', aval: '50% múltipla escolha + 50% discursiva', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  Herança: extends, super','  @Override e polimorfismo','  Classes abstratas e interfaces','  Relacionamentos (comp./agr.)','  Exceções: try/catch/throws','  Coleções: ArrayList, HashMap'], guia: null, tempos: [] },
  { sem: 27, tri: 2, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'RPT do 2º trimestre', hab: 'Consolidar aprendizagens do 2º trimestre', aval: 'RPT substitui nota se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PONTOS CRÍTICOS:','→ Herança e super()','→ Diferença abstrata vs interface','→ Polimorfismo e lista polimórfica','→ try/catch e throws',' ','ESTRATÉGIA:','→ Correção comentada','→ Exercício de reforço com hierarquia'], guia: null, tempos: [] },

  // ─── 3º TRIMESTRE ─────────────────────────────────────────
  { sem: 28, tri: 3, tema: 'Padrões de Projeto: introdução ao Singleton e ao Builder', tipo: 'teoria', comp: 'Reconhecer e aplicar padrões de projeto criacionais', hab: 'Implementar Singleton para garantir instância única de uma classe', aval: 'Singleton de configuração do sistema implementado (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['DESIGN PATTERN — SINGLETON','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Config {','  private static Config instancia;','  private String servidor;',' ','  private Config() {} // construtor privado',' ','  public static Config getInstancia() {','    if (instancia == null)','      instancia = new Config();','    return instancia;','  }','}',' ','Config c1 = Config.getInstancia();','Config c2 = Config.getInstancia();','// c1 == c2 → mesma instância!'], guia: null, tempos: [] },
  { sem: 29, tri: 3, tema: 'Padrão Factory Method — criação desacoplada de objetos', tipo: 'pratica', comp: 'Aplicar Factory Method para desacoplar criação de objetos', hab: 'Criar uma Factory que instancia subclasses de acordo com parâmetros', aval: 'Factory de Formas geométricas ou meios de pagamento (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['FACTORY METHOD — SEM. 29','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class PagamentoFactory {','  public static Pagamento criar(String tipo) {','    switch (tipo) {','      case "pix":    return new Pix();','      case "cartao": return new Cartao();','      default: throw new IllegalArgument...','    }','  }','}',' ','Pagamento p =','  PagamentoFactory.criar("pix");','p.processar();'], guia: null, tempos: [] },
  { sem: 30, tri: 3, tema: 'Princípios SOLID: S — Single Responsibility e O — Open/Closed', tipo: 'teoria', comp: 'Compreender e aplicar os dois primeiros princípios SOLID', hab: 'Refatorar código violando SRP e OCP para versões SOLID-compliant', aval: 'Refatoração de classe que viola SRP (AQL — produção textual)', rec: 'Laboratório, VS Code, exemplos de código antes/depois', quadro: ['SOLID — S e O — SEM. 30','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','S — Single Responsibility Principle','  Uma classe = uma responsabilidade','  ✗ Aluno que salva no banco E envia email','  ✓ Aluno | AlunoDAO | AlunoNotificacao',' ','O — Open/Closed Principle','  Aberto p/ extensão, fechado p/ modificação','  Usar interface/abstrata p/ adicionar','  comportamento SEM mudar código existente'], guia: null, tempos: [] },
  { sem: 31, tri: 3, tema: 'Princípios SOLID: L, I e D — Liskov, Interface Segregation, Dependency Inversion', tipo: 'teoria', comp: 'Compreender os três últimos princípios SOLID', hab: 'Identificar violações de LSP, ISP e DIP em código Java', aval: 'Análise de código com violações SOLID identificadas (AQL)', rec: 'Laboratório, VS Code, projetor', quadro: ['SOLID — L, I, D — SEM. 31','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','L — Liskov Substitution','  Subclasse deve substituir superclasse','  sem quebrar o comportamento',' ','I — Interface Segregation','  Interfaces pequenas e específicas','  ✗ Interface com 10 métodos desnecessários',' ','D — Dependency Inversion','  Dependa de abstrações, não de concretos','  Injete dependências via construtor'], guia: null, tempos: [] },
  { sem: 32, tri: 3, tema: 'Persistência de dados: leitura e escrita em arquivos com Java', tipo: 'pratica', comp: 'Persistir dados de objetos em arquivos texto e binário', hab: 'Usar FileWriter/FileReader e serialização Java para salvar objetos', aval: 'Sistema que salva e carrega lista de objetos em arquivo (AQL)', rec: 'Laboratório, VS Code, JDK', quadro: ['PERSISTÊNCIA — ARQUIVOS — SEM. 32','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','// Escrever','FileWriter fw = new FileWriter("dados.txt");','fw.write(aluno.getNome() + ";" + aluno.getNota());','fw.close();',' ','// Ler','BufferedReader br = new BufferedReader(','  new FileReader("dados.txt"));','String linha = br.readLine();',' ','// Serialização','// implements Serializable','ObjectOutputStream oos = ...','oos.writeObject(listaAlunos);'], guia: null, tempos: [] },
  { sem: 33, tri: 3, tema: 'Conexão com banco de dados: JDBC — SELECT, INSERT e PreparedStatement', tipo: 'pratica', comp: 'Integrar aplicações Java a bancos de dados relacionais com JDBC', hab: 'Conectar ao MySQL via JDBC e executar operações CRUD com PreparedStatement', aval: 'Sistema Java que persiste objetos no MySQL (AQL — produção)', rec: 'Laboratório, VS Code, JDK, MySQL, XAMPP, driver mysql-connector', quadro: ['JDBC — SEM. 33','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','Connection con = DriverManager.getConnection(','  "jdbc:mysql://localhost/escola","root","");',' ','// Consulta','PreparedStatement ps =','  con.prepareStatement("SELECT * FROM alunos");','ResultSet rs = ps.executeQuery();','while (rs.next()) { rs.getString("nome"); }',' ','// Inserção','ps = con.prepareStatement(','  "INSERT INTO alunos(nome) VALUES (?)");','ps.setString(1, nome); ps.executeUpdate();'], guia: null, tempos: [] },
  { sem: 34, tri: 3, tema: 'Projeto Final — planejamento: UML, requisitos e modelagem do banco', tipo: 'projeto', comp: 'Planejar e documentar projeto orientado a objetos completo', hab: 'Elaborar diagrama UML, requisitos funcionais e modelo ER do banco', aval: 'Entrega do plano de projeto com UML (AQL — produção textual)', rec: 'Laboratório, draw.io, template de documentação', quadro: ['PROJETO FINAL — PLANEJAMENTO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','DOCUMENTAÇÃO MÍNIMA:','  1. Tema e justificativa','  2. Diagrama de classes UML','  3. Diagrama ER do banco','  4. Requisitos funcionais','  5. Divisão de tarefas','  6. Cronograma de entrega',' ','CRITÉRIOS: uso de herança, interfaces,','  exceções, coleções e JDBC'], guia: null, tempos: [] },
  { sem: 35, tri: 3, tema: 'Projeto Final — desenvolvimento parte 1: modelo e persistência', tipo: 'projeto', comp: 'Implementar as classes de domínio e a camada de persistência', hab: 'Codificar classes-modelo, DAOs e conexão JDBC do projeto final', aval: 'Checkpoint 1 — modelo + banco funcionando', rec: 'Laboratório, VS Code, JDK, MySQL', quadro: ['PROJETO FINAL — CHECKPOINT 1','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 35:','→ Banco de dados criado','→ Classes de modelo completas','→ Pelo menos 1 DAO com INSERT/SELECT','→ Exceções customizadas no modelo','→ UML atualizada'], guia: null, tempos: [] },
  { sem: 36, tri: 3, tema: 'Projeto Final — desenvolvimento parte 2: lógica e integração', tipo: 'projeto', comp: 'Implementar a lógica de negócio e integrar todas as camadas', hab: 'Codificar serviços, validações e menu de navegação completo', aval: 'Checkpoint 2 — sistema integrado e funcional', rec: 'Laboratório, VS Code, JDK, MySQL', quadro: ['PROJETO FINAL — CHECKPOINT 2','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 36:','→ Todas as operações CRUD prontas','→ Exceções tratadas em todas as entradas','→ Herança/polimorfismo em uso','→ Interface implementada em mín. 1 classe','→ Sem erros críticos de execução'], guia: null, tempos: [] },
  { sem: 37, tri: 3, tema: 'Projeto Final — testes, refatoração e documentação final', tipo: 'projeto', comp: 'Finalizar, refatorar e documentar o projeto completo', hab: 'Corrigir bugs, aplicar boas práticas SOLID e completar a documentação', aval: 'Sistema testado + documentação entregue', rec: 'Laboratório, VS Code, JDK, checklist SOLID', quadro: ['PROJETO FINAL — ENTREGA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ENTREGÁVEIS:','  1. Código completo (GitHub ou .zip)','  2. Diagrama UML final (classes)','  3. Documentação técnica (PDF)','  4. Manual de uso breve',' ','RUBRICA:','  POO: herança|interfaces|encapsulamento','  SOLID|Exceções|JDBC|Código limpo'], guia: null, tempos: [] },
  { sem: 38, tri: 3, tema: 'AQL — banca avaliadora do Projeto Final', tipo: 'aval', comp: 'AQL final: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar e defender projeto com demonstração de código ao vivo', aval: 'AQL final — nota mínima 6,0 — IN SUPEN 4/2024', rec: 'Projetor, ficha de avaliação da banca', quadro: ['AQL FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','BANCA AVALIADORA','  Produção Textual (40%):','    → Código + UML + documentação','  Oralidade (30%):','    → Demo ao vivo + perguntas técnicas','  Participação (30%):','    → Engajamento no trimestre',' ','DURAÇÃO: 10 min por grupo/aluno'], guia: null, tempos: [] },
  { sem: 39, tri: 3, tema: 'AQT — Avaliação Específica Final: padrões, SOLID e JDBC', tipo: 'aval', comp: 'AQT final: avaliação quantitativa do 3º trimestre', hab: 'Demonstrar domínio de padrões de projeto, SOLID, persistência e JDBC', aval: '50% objetiva + 50% discursiva — escala 0 a 10', rec: 'Prova impressa, sala de aula', quadro: ['AQT FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  Padrões: Singleton, Factory','  Princípios SOLID (S, O, L, I, D)','  Persistência em arquivo e JDBC','  Lambda e Streams',' ','5 objetivas (50%) + 2 discursivas (50%)'], guia: null, tempos: [] },
  { sem: 40, tri: 3, tema: 'Conselho de Classe, revisão anual e encerramento', tipo: 'aval', comp: 'Avaliação global e encerramento do ano letivo', hab: 'Refletir sobre o percurso e identificar aprendizagens', aval: 'Conselho de Classe — art. 17 Regimento SEDUC-PI', rec: 'Ficha do Conselho de Classe, diário de bordo', quadro: ['ENCERRAMENTO — SEM. 40','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONSELHO DE CLASSE:','→ Análise da turma (rendimento)','→ Alunos com nota < 6,0','→ Deliberação: aprovação / PF',' ','PROVA FINAL (PF):','→ Para alunos com MA < 6,0','→ Frequência mínima 75%'], guia: null, tempos: [] }
];
