// ============================================================
// SEQUÊNCIA DIDÁTICA — Programação para Web — 3º Ano
// 40 semanas letivas — 3 trimestres — SEDUC-PI PPC 2024
// Edite os temas, competências e conteúdos conforme necessário
// ============================================================

const AULAS = [
  // ─── 1º TRIMESTRE ─────────────────────────────────────────
  {
    sem: 1, tri: 1,
    tema: 'Arquitetura web, cliente x servidor, HTTP/HTTPS',
    tipo: 'teoria',
    comp: 'Compreender os fundamentos da arquitetura web',
    hab: 'Identificar como funciona HTTP e a comunicação cliente-servidor',
    aval: 'Participação em debate + mapa conceitual (AQL)',
    rec: 'Projetor, lousa, exercício de fixação',
    quadro: [
      'PROGRAMAÇÃO PARA WEB — SEM. 1',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'ARQUITETURA WEB',
      '  Cliente → Request → Servidor',
      '  Servidor → Response → Cliente',
      ' ',
      'HTTP vs HTTPS',
      '  HTTP: sem criptografia',
      '  HTTPS: com SSL/TLS (cadeado)',
      ' ',
      'FRONT-END: HTML | CSS | JS',
      'BACK-END:  PHP | Node | Python'
    ],
    guia: [
      { num: 1, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Abertura e contextualização (10 min)', desc: 'Pergunte: "Quando você acessa o Instagram, o que acontece entre seu celular e o servidor?" Deixe 2-3 alunos responderem. Anote as respostas no quadro sem corrigir ainda — ativa o conhecimento prévio.', dica: 'Não corrija os erros agora. Volte a eles no final para mostrar o que aprenderam.', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Explicação: arquitetura cliente-servidor (15 min)', desc: 'Desenhe no quadro: CLIENTE → (request) → SERVIDOR → (response) → CLIENTE. Explique cada seta com exemplos reais. Mostre a diferença HTTP vs HTTPS abrindo o navegador e mostrando o cadeado em sites reais.', dica: 'Prática rápida: abra F12 > Network no Chrome e mostre os requests acontecendo em tempo real.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#3C3489', bg: '#EEEDFE', titulo: 'Front-end vs Back-end (10 min)', desc: 'Escreva no quadro: FRONT-END (HTML, CSS, JS) e BACK-END (PHP, Node, Python, BD). Use a analogia do restaurante: front é o salão, back é a cozinha.', dica: '"Você não vê a cozinha, mas a comida chega pronta. No site, você não vê o PHP, mas os dados aparecem."', dicaBg: '#EEEDFE', dicaCor: '#26215C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Verificação da aprendizagem (10 min)', desc: 'Faça 3 perguntas orais: (1) Papel do cliente? (2) Diferença HTTP vs HTTPS? (3) Uma tecnologia de front e uma de back? Escolha alunos diferentes. Anote participação (AQL).', dica: 'AQL — Participação: registre quem respondeu. Compõe os 30% de participação da avaliação qualitativa.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese e tarefa (15 min)', desc: 'Copie o esquema final no quadro. Peça que copiem no caderno. Síntese em 3 frases. Tarefa: acessar 3 sites, verificar HTTPS e identificar o que é front e back.', dica: 'Conecte sempre ao próximo conteúdo: "Na próxima aula vocês já vão escrever código HTML."', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Abertura', t: '10 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Explicação', t: '15 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: 'Front vs Back', t: '10 min', bg: '#EEEDFE', c: '#3C3489' },
      { label: 'Verificação', t: '10 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '15 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  {
    sem: 2, tri: 1,
    tema: 'HTML5 — estrutura semântica: header, main, section, article, footer',
    tipo: 'pratica',
    comp: 'Criar páginas web estruturadas com HTML semântico',
    hab: 'Aplicar tags semânticas do HTML5 em páginas reais',
    aval: 'Entrega de página HTML comentada (AQL — produção textual)',
    rec: 'Laboratório de informática, VS Code, navegador',
    quadro: [
      'HTML5 — ESTRUTURA SEMÂNTICA',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'Tags semânticas:',
      '  <header>  → cabeçalho da página',
      '  <nav>     → menu de navegação',
      '  <main>    → conteúdo principal',
      '  <section> → seção temática',
      '  <article> → conteúdo independente',
      '  <footer>  → rodapé da página',
      ' ',
      'Boa prática: evitar <div> genérico'
    ],
    guia: [
      { num: 1, cor: '#185FA5', bg: '#E6F1FB', titulo: 'Retomada da tarefa (5 min)', desc: 'Peça a 2 alunos para compartilhar o que encontraram nos 3 sites (HTTPS e front/back). Anote quem trouxe a tarefa (participação AQL). Anuncie: "Hoje vocês escrevem a primeira linha de código HTML5."', dica: 'Registre quem trouxe a tarefa — compõe participação AQL (30%).', dicaBg: '#E6F1FB', dicaCor: '#0C447C' },
      { num: 2, cor: '#1E8449', bg: '#D5F5E3', titulo: 'Demonstração no projetor (10 min)', desc: 'Abra VS Code no projetor. Crie index.html do zero com ! + Tab. Adicione as tags semânticas uma a uma mostrando o resultado no navegador a cada adição.', dica: 'Mostre que o navegador renderiza mesmo sem CSS — isso impressiona os iniciantes.', dicaBg: '#D5F5E3', dicaCor: '#196F3D' },
      { num: 3, cor: '#3C3489', bg: '#EEEDFE', titulo: 'Prática guiada — todos codificam juntos (20 min)', desc: 'Peça que TODOS abram VS Code e criem o mesmo arquivo junto com você. Dite o código devagar. Circule pela sala verificando as telas. Pare 3 vezes para perguntar quem tem dúvida.', dica: 'Se um aluno tiver problema técnico, sente um colega ao lado para ajudar. Não pare a aula por 1 aluno.', dicaBg: '#EEEDFE', dicaCor: '#26215C' },
      { num: 4, cor: '#854F0B', bg: '#FAEEDA', titulo: 'Desafio individual (20 min)', desc: 'Passe o desafio: "Crie uma página HTML5 com estrutura semântica completa, título, parágrafo sobre você e um link. Salve como meu_perfil.html." Circule e anote quem entrega completo (AQL — produção textual 40%).', dica: 'AQL: anote os nomes de quem entrega com todas as tags semânticas corretas.', dicaBg: '#FAEEDA', dicaCor: '#633806' },
      { num: 5, cor: '#444441', bg: '#F1EFE8', titulo: 'Síntese (5 min)', desc: 'Mostre 2-3 páginas dos alunos no projetor (com permissão). Elogie o correto. Anuncie próxima aula: "Formulários HTML — a parte mais usada em sistemas web."', dica: '"Quem acabou de criar sua primeira página HTML5 — isso é código de verdade rodando no seu computador."', dicaBg: '#F1EFE8', dicaCor: '#444441' }
    ],
    tempos: [
      { label: 'Retomada', t: '5 min', bg: '#E6F1FB', c: '#185FA5' },
      { label: 'Demo', t: '10 min', bg: '#D5F5E3', c: '#1E8449' },
      { label: 'Prática guiada', t: '20 min', bg: '#EEEDFE', c: '#3C3489' },
      { label: 'Desafio', t: '20 min', bg: '#FAEEDA', c: '#854F0B' },
      { label: 'Síntese', t: '5 min', bg: '#F1EFE8', c: '#444441' }
    ]
  },
  { sem: 3, tri: 1, tema: 'HTML5 — formulários, tabelas e elementos multimídia', tipo: 'pratica', comp: 'Criar páginas com formulários interativos', hab: 'Implementar formulários HTML com campos e validação básica', aval: 'Formulário de cadastro completo (AQL)', rec: 'Laboratório, VS Code, navegador', quadro: ['HTML5 — FORMULÁRIOS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','<form action="" method="post">','  <input type="text|email|password">','  <select> | <textarea>','  <button type="submit">Enviar</button>','</form>',' ','TABELAS','  <table><thead><tr><th>','  <tbody><tr><td>'], guia: null, tempos: [] },
  { sem: 4, tri: 1, tema: 'CSS3 — seletores, box model, cores e tipografia', tipo: 'pratica', comp: 'Estilizar páginas web com CSS3', hab: 'Aplicar seletores, cores, fontes e espaçamento', aval: 'Estilização de página HTML (AQL)', rec: 'Laboratório, VS Code, DevTools', quadro: ['CSS3 — SELETORES E BOX MODEL','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','SELETORES','  elemento | .classe | #id | :hover','BOX MODEL','  content → padding → border → margin','TIPOGRAFIA','  font-family | font-size | color'], guia: null, tempos: [] },
  { sem: 5, tri: 1, tema: 'CSS3 — Flexbox: justify-content, align-items, flex-wrap', tipo: 'pratica', comp: 'Criar layouts responsivos com Flexbox', hab: 'Usar Flexbox para organizar elementos em linha e coluna', aval: 'Layout com Flexbox (AQL — produção)', rec: 'Laboratório, VS Code, flexboxfroggy.com', quadro: ['CSS3 — FLEXBOX','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','display: flex','flex-direction: row | column','justify-content: center | space-between','align-items: center | flex-start','flex-wrap: wrap | nowrap',' ','Filho: flex: 1 | align-self: center'], guia: null, tempos: [] },
  { sem: 6, tri: 1, tema: 'CSS3 — Grid Layout e design responsivo com media queries', tipo: 'pratica', comp: 'Implementar design responsivo', hab: 'Usar Grid e media queries para adaptar layouts', aval: 'Layout responsivo com Grid (AQL)', rec: 'Laboratório, VS Code, DevTools mobile view', quadro: ['CSS3 — GRID E RESPONSIVIDADE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','display: grid','grid-template-columns: 1fr 2fr','gap: 16px',' ','MEDIA QUERIES','@media (max-width: 768px) {','  .container { flex-direction: column }','}'], guia: null, tempos: [] },
  { sem: 7, tri: 1, tema: 'Projeto 1 — página estática responsiva (HTML + CSS)', tipo: 'projeto', comp: 'Integrar HTML5 e CSS3 em projeto real', hab: 'Construir página completa responsiva', aval: 'Entrega do projeto com rubrica AQL + AQT', rec: 'Laboratório, VS Code', quadro: ['PROJETO 1 — PÁGINA ESTÁTICA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','REQUISITOS MÍNIMOS:','  1. HTML semântico completo','  2. CSS externo com Flexbox/Grid','  3. Responsivo (mín. 2 breakpoints)','  4. Formulário de contato',' ','RUBRICA: Estrutura|Estilo|Responsiv.|Código'], guia: null, tempos: [] },
  { sem: 8, tri: 1, tema: 'JavaScript — variáveis, tipos, operadores e funções', tipo: 'teoria', comp: 'Programar no lado cliente com JavaScript', hab: 'Declarar variáveis e criar funções em JS', aval: 'Exercício de fixação (AQL — participação)', rec: 'Laboratório, VS Code, console do navegador', quadro: ['JAVASCRIPT — FUNDAMENTOS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','let nome = "Maria"','const PI = 3.14',' ','TIPOS: string|number|boolean|array|object',' ','function somar(a, b) { return a + b }','const dobro = x => x * 2'], guia: null, tempos: [] },
  { sem: 9, tri: 1, tema: 'JavaScript — manipulação do DOM: querySelector, addEventListener', tipo: 'pratica', comp: 'Manipular eventos e interações na página', hab: 'Selecionar elementos e responder a eventos', aval: 'Mini projeto: botão interativo (AQL)', rec: 'Laboratório, VS Code, DevTools', quadro: ['JAVASCRIPT — DOM','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','document.querySelector("#id")','document.querySelectorAll(".classe")',' ','el.textContent = "Novo texto"','el.classList.add("ativo")',' ','el.addEventListener("click", funcao)'], guia: null, tempos: [] },
  { sem: 10, tri: 1, tema: 'JavaScript — bibliotecas embutidas e validação de formulários', tipo: 'pratica', comp: 'Desenvolver formulários com validação JS', hab: 'Validar campos com JavaScript antes do envio', aval: 'Formulário com validação JS (AQL)', rec: 'Laboratório, VS Code', quadro: ['JS — VALIDAÇÃO DE FORMULÁRIO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','form.addEventListener("submit", e => {','  e.preventDefault()','  if (campo.value === "") {','    alert("Campo obrigatório")','  }','}','Math | Date | JSON — objetos globais'], guia: null, tempos: [] },
  { sem: 11, tri: 1, tema: 'AQL — seminário e portfólio HTML/CSS/JS', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar e defender projeto com clareza técnica', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CRITÉRIOS (IN SUPEN 4/2024):','  Produção Textual: 40%','    → portfólio + documentação','  Oralidade: 30%','    → apresentação e defesa oral','  Participação: 30%','    → engajamento nas aulas',' ','NOTA MÍNIMA: 6,0 pontos'], guia: null, tempos: [] },
  { sem: 12, tri: 1, tema: 'AQT — Avaliação Específica: 50% objetiva + 50% discursiva', tipo: 'aval', comp: 'AQT: avaliação quantitativa conforme IN SUPEN 4/2024', hab: 'Demonstrar domínio dos conteúdos do 1º trimestre', aval: 'AQT — escala 0 a 10, integra média trimestral', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 1º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','FORMATO (IN SUPEN 4/2024):','  50% Múltipla Escolha (5 questões)','  50% Discursiva (2 questões)',' ','CONTEÚDO:','  HTML5 | CSS3 | JavaScript | DOM'], guia: null, tempos: [] },
  { sem: 13, tri: 1, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'Recuperação Paralela Trimestral conforme SEDUC-PI', hab: 'Recuperar e consolidar aprendizagens do 1º trimestre', aval: 'RPT — nota substitui trimestral se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — RECUPERAÇÃO PARALELA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','A nota RPT SUBSTITUI a média','trimestral SE for ≥ 6,0',' ','ESTRATÉGIA:','→ Correção comentada da prova','→ Revisão dos pontos críticos','→ Exercício de reforço individual'], guia: null, tempos: [] },

  // ─── 2º TRIMESTRE ─────────────────────────────────────────
  { sem: 14, tri: 2, tema: 'PHP — introdução, sintaxe, variáveis e tipos de dados', tipo: 'teoria', comp: 'Programação no servidor com PHP', hab: 'Identificar a sintaxe básica e declarar variáveis em PHP', aval: 'Exercício: script PHP simples', rec: 'Laboratório, VS Code, XAMPP', quadro: ['PHP — INTRODUÇÃO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','<?php','  $nome = "Maria";','  $idade = 17;','  $ativo = true;','  echo "Olá, " . $nome;','?>',' ','TIPOS: string|int|float|bool|array'], guia: null, tempos: [] },
  { sem: 15, tri: 2, tema: 'PHP — estruturas de controle: if, else, for, while, foreach', tipo: 'pratica', comp: 'Controlar o fluxo de execução com PHP', hab: 'Implementar condicionais e laços de repetição em PHP', aval: 'Lista de exercícios — algoritmos em PHP (AQL)', rec: 'Laboratório, XAMPP, VS Code', quadro: ['PHP — ESTRUTURAS DE CONTROLE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','if ($nota >= 6) { echo "Aprovado"; }','else { echo "Reprovado"; }',' ','for ($i=1; $i<=10; $i++) { echo $i; }',' ','foreach ($alunos as $aluno) {','  echo $aluno["nome"];','}'], guia: null, tempos: [] },
  { sem: 16, tri: 2, tema: 'PHP — funções, arrays e manipulação de strings', tipo: 'pratica', comp: 'Organizar código PHP com funções e arrays', hab: 'Criar funções reutilizáveis e manipular arrays em PHP', aval: 'Exercício: funções de cálculo e array de alunos', rec: 'Laboratório, XAMPP, VS Code', quadro: ['PHP — FUNÇÕES E ARRAYS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','function calcularMedia($n1, $n2) {','  return ($n1 + $n2) / 2;','}',' ','$alunos = ["Ana", "João", "Maria"];','echo count($alunos);',' ','strtoupper() | strlen() | str_replace()'], guia: null, tempos: [] },
  { sem: 17, tri: 2, tema: 'PHP — formulários HTML + GET/POST + validação no servidor', tipo: 'pratica', comp: 'Desenvolver formulários interativos com PHP', hab: 'Processar dados de formulários com $_GET e $_POST', aval: 'Formulário PHP com validação no servidor (AQL)', rec: 'Laboratório, XAMPP, VS Code', quadro: ['PHP — FORMULÁRIOS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','$_POST["nome"]','$_GET["pagina"]',' ','VALIDAR','if (empty($_POST["nome"])) {','  echo "Campo obrigatório!";','}',' ','htmlspecialchars($dado)'], guia: null, tempos: [] },
  { sem: 18, tri: 2, tema: 'PHP + MySQL — conexão PDO, SELECT, INSERT, UPDATE, DELETE', tipo: 'pratica', comp: 'Integrar banco de dados MySQL ao sistema web', hab: 'Conectar PHP ao MySQL e executar operações CRUD', aval: 'CRUD simples funcional (AQL — produção)', rec: 'Laboratório, XAMPP, phpMyAdmin, VS Code', quadro: ['PHP + MYSQL — CRUD','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','$pdo = new PDO("mysql:host=localhost;','  dbname=escola", "root", "");',' ','$stmt = $pdo->query("SELECT * FROM alunos");','$alunos = $stmt->fetchAll();',' ','$stmt = $pdo->prepare("INSERT INTO alunos','  (nome) VALUES (?)");','$stmt->execute([$nome]);'], guia: null, tempos: [] },
  { sem: 19, tri: 2, tema: 'Controle de sessão e estado — session_start, cookies', tipo: 'pratica', comp: 'Controlar estado e sessão em sistemas web', hab: 'Implementar login/logout com session e cookies', aval: 'Sistema de login simples funcional (AQL)', rec: 'Laboratório, XAMPP, VS Code', quadro: ['PHP — SESSÃO E COOKIES','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','session_start();','$_SESSION["usuario"] = "Maria";','unset($_SESSION["usuario"]);','session_destroy();',' ','setcookie("tema", "escuro", time()+86400);','echo $_COOKIE["tema"];'], guia: null, tempos: [] },
  { sem: 20, tri: 2, tema: 'Projeto 2 — sistema de cadastro com PHP + MySQL', tipo: 'projeto', comp: 'Integrar PHP, MySQL e formulários em sistema real', hab: 'Construir CRUD completo com login, cadastro e listagem', aval: 'Sistema funcional — rubrica AQL + AQT', rec: 'Laboratório, XAMPP, VS Code, phpMyAdmin', quadro: ['PROJETO 2 — SISTEMA DE CADASTRO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','REQUISITOS:','  1. Login com sessão','  2. Cadastro (INSERT)','  3. Listagem (SELECT)','  4. Edição (UPDATE)','  5. Exclusão (DELETE)','  6. Validação no servidor'], guia: null, tempos: [] },
  { sem: 21, tri: 2, tema: 'PHP Orientado a Objetos — classes, objetos, encapsulamento', tipo: 'teoria', comp: 'Aplicar POO no desenvolvimento web com PHP', hab: 'Criar classes e instanciar objetos em PHP', aval: 'Exercício: classe Aluno com getters e setters', rec: 'Laboratório, VS Code', quadro: ['PHP OO — CLASSES','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Aluno {','  private $nome;','  public function getNome() {','    return $this->nome;','  }','  public function setNome($n) {','    $this->nome = $n;','  }','}',' ','$a = new Aluno();'], guia: null, tempos: [] },
  { sem: 22, tri: 2, tema: 'PHP OO — herança, polimorfismo e interfaces', tipo: 'pratica', comp: 'Aplicar herança e polimorfismo em PHP', hab: 'Implementar hierarquia de classes com herança em PHP', aval: 'Implementação de herança (AQL — produção)', rec: 'Laboratório, VS Code', quadro: ['PHP OO — HERANÇA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','class Pessoa { public $nome; }',' ','class Aluno extends Pessoa {','  public $matricula;','  public function apresentar() {','    return "Aluno: ".$this->nome;','  }','}',' ','INTERFACE: contrato de métodos'], guia: null, tempos: [] },
  { sem: 23, tri: 2, tema: 'Padrão MVC — Model, View, Controller na teoria e prática', tipo: 'teoria', comp: 'Aplicar o padrão MVC no desenvolvimento web', hab: 'Identificar e separar as camadas M, V e C', aval: 'Diagrama MVC do projeto + exercício conceitual', rec: 'Projetor, laboratório, VS Code', quadro: ['PADRÃO MVC','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','M → MODEL','  Lógica de negócio + BD','  Ex: Aluno.php (classe + SQL)',' ','V → VIEW','  Interface visual (HTML/CSS)',' ','C → CONTROLLER','  Recebe req → chama model','  → renderiza view'], guia: null, tempos: [] },
  { sem: 24, tri: 2, tema: 'MVC — implementação de sistema com separação de camadas', tipo: 'pratica', comp: 'Desenvolver sistema web organizado em MVC', hab: 'Refatorar projeto em estrutura MVC funcional', aval: 'Sistema em MVC funcional (AQL — produção)', rec: 'Laboratório, VS Code, XAMPP', quadro: ['MVC — ESTRUTURA DE PASTAS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','projeto/','  /models/      → Aluno.php','  /views/       → listagem.php','  /controllers/ → AlunoController.php','  /config/      → database.php','  index.php     → ponto de entrada'], guia: null, tempos: [] },
  { sem: 25, tri: 2, tema: 'AQL — apresentação do Projeto 2', tipo: 'aval', comp: 'AQL: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar sistema desenvolvido com argumentação técnica', aval: 'AQL conforme IN SUPEN Nº 4/2024 — nota mínima 6,0', rec: 'Projetor, ficha de avaliação SEDUC-PI', quadro: ['AQL — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','APRESENTAÇÃO DO PROJETO 2','  Produção Textual (40%):','    → Documentação técnica','  Oralidade (30%):','    → Demo ao vivo + perguntas','  Participação (30%):','    → Engajamento no trimestre'], guia: null, tempos: [] },
  { sem: 26, tri: 2, tema: 'AQT — Avaliação Específica: PHP, BD e MVC', tipo: 'aval', comp: 'AQT: avaliação quantitativa do 2º trimestre', hab: 'Demonstrar domínio de PHP, MySQL e MVC', aval: '50% múltipla escolha + 50% discursiva', rec: 'Prova impressa, sala de aula', quadro: ['AQT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  PHP: sintaxe, funções, arrays','  MySQL: CRUD com PDO','  Sessão e cookies','  PHP OO: classes, herança','  Padrão MVC'], guia: null, tempos: [] },
  { sem: 27, tri: 2, tema: 'Correção, feedback e RPT (Recuperação Paralela Trimestral)', tipo: 'aval', comp: 'RPT do 2º trimestre', hab: 'Consolidar aprendizagens do 2º trimestre', aval: 'RPT substitui nota se ≥ 6,0', rec: 'Material de revisão, exercícios de reforço', quadro: ['RPT — 2º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PONTOS CRÍTICOS:','→ Conexão PHP + MySQL (PDO)','→ Sessão e autenticação','→ Estrutura MVC',' ','ESTRATÉGIA:','→ Correção comentada','→ Exercício de reforço PHP + BD'], guia: null, tempos: [] },

  // ─── 3º TRIMESTRE ─────────────────────────────────────────
  { sem: 28, tri: 3, tema: 'Frameworks web — introdução ao Laravel ou CodeIgniter', tipo: 'teoria', comp: 'Utilizar frameworks para otimizar desenvolvimento', hab: 'Identificar vantagens dos frameworks e configurar ambiente', aval: 'Instalação e primeiro projeto com framework', rec: 'Laboratório, Composer, VS Code, terminal', quadro: ['FRAMEWORKS — INTRODUÇÃO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','Por que usar framework?','→ Código organizado (MVC nativo)','→ Segurança embutida','→ Comunidade e documentação',' ','INSTALAÇÃO (Laravel):','composer create-project laravel/laravel app',' ','ESTRUTURA: /app /routes /resources /database'], guia: null, tempos: [] },
  { sem: 29, tri: 3, tema: 'Framework — rotas, controllers e views com template engine', tipo: 'pratica', comp: 'Desenvolver com rotas e controllers em framework', hab: 'Criar rotas, controllers e views com Blade', aval: 'Aplicação básica com rotas funcionais', rec: 'Laboratório, Composer, VS Code', quadro: ['FRAMEWORK — ROTAS E VIEWS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','Route::get("/alunos",','  [AlunoController::class, "index"]);',' ','public function index() {','  $alunos = Aluno::all();','  return view("alunos.index",','    compact("alunos"));','}',' ','VIEW (Blade): {{ $aluno->nome }}'], guia: null, tempos: [] },
  { sem: 30, tri: 3, tema: 'Framework — migrations, models e Eloquent ORM', tipo: 'pratica', comp: 'Gerenciar banco de dados com ORM', hab: 'Criar migrations e usar Eloquent para operações no banco', aval: 'CRUD completo com ORM funcional', rec: 'Laboratório, Composer, MySQL, VS Code', quadro: ['ELOQUENT ORM','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','php artisan make:migration create_alunos',' ','class Aluno extends Model {','  protected $fillable = ["nome","email"];','}',' ','Aluno::all()','Aluno::find($id)','Aluno::create(["nome" => $nome])'], guia: null, tempos: [] },
  { sem: 31, tri: 3, tema: 'Geração de relatórios e gráficos com PHP e bibliotecas', tipo: 'pratica', comp: 'Gerar relatórios e interfaces visuais de dados', hab: 'Usar bibliotecas para exportar PDF e gerar gráficos', aval: 'Relatório funcional com dados do banco', rec: 'Laboratório, DOMPDF, Chart.js', quadro: ['RELATÓRIOS E GRÁFICOS','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','PDF (DOMPDF):','$pdf->loadView("relatorio", $dados);','$pdf->download("relatorio.pdf");',' ','GRÁFICO (Chart.js):','<canvas id="grafico"></canvas>','new Chart(ctx, { type: "bar", ...})'], guia: null, tempos: [] },
  { sem: 32, tri: 3, tema: 'Segurança web — SQL Injection, XSS, validação e sanitização', tipo: 'teoria', comp: 'Aplicar boas práticas de segurança em sistemas web', hab: 'Identificar e prevenir vulnerabilidades comuns da web', aval: 'Análise de código com falhas de segurança (AQL)', rec: 'Laboratório, VS Code, OWASP Top 10', quadro: ['SEGURANÇA WEB','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','SQL INJECTION','  RUIM: "SELECT * WHERE id=".$_GET["id"]','  BOM: prepared statements (PDO)',' ','XSS','  RUIM: echo $_POST["comentario"]','  BOM: echo htmlspecialchars($dado)',' ','→ HTTPS | senha com hash | CSRF token'], guia: null, tempos: [] },
  { sem: 33, tri: 3, tema: 'Deploy — publicação de aplicação web em servidor real', tipo: 'pratica', comp: 'Publicar e testar aplicações web em produção', hab: 'Configurar servidor e publicar aplicação PHP', aval: 'Aplicação publicada e acessível via URL', rec: 'Laboratório, Hostinger/InfinityFree, FTP', quadro: ['DEPLOY — PUBLICAÇÃO WEB','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ETAPAS:','  1. Exportar BD (mysqldump)','  2. Upload via FTP/cPanel','  3. Configurar .env (BD, URL)','  4. Importar BD no servidor','  5. Testar todas as funções',' ','FileZilla (FTP) | cPanel | phpMyAdmin'], guia: null, tempos: [] },
  { sem: 34, tri: 3, tema: 'Projeto Final — definição de tema, planejamento e divisão de tarefas', tipo: 'projeto', comp: 'Planejar e documentar projeto de aplicação web completo', hab: 'Elaborar escopo, estrutura do banco e divisão de tarefas', aval: 'Entrega do plano de projeto (AQL — produção textual)', rec: 'Laboratório, template de documentação', quadro: ['PROJETO FINAL — PLANEJAMENTO','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','DOCUMENTAÇÃO MÍNIMA:','  1. Tema e justificativa','  2. Requisitos funcionais','  3. Diagrama ER do banco','  4. Wireframe das telas','  5. Divisão de tarefas','  6. Cronograma de entrega'], guia: null, tempos: [] },
  { sem: 35, tri: 3, tema: 'Projeto Final — desenvolvimento: front-end e back-end', tipo: 'projeto', comp: 'Desenvolver front-end e back-end integrados', hab: 'Implementar funcionalidades definidas no planejamento', aval: 'Checkpoint 1 — progresso acompanhado', rec: 'Laboratório, VS Code, XAMPP', quadro: ['PROJETO FINAL — CHECKPOINT 1','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 35:','→ Banco de dados criado','→ Login e autenticação OK','→ Pelo menos 1 CRUD completo','→ Layout responsivo iniciado'], guia: null, tempos: [] },
  { sem: 36, tri: 3, tema: 'Projeto Final — integração com banco de dados e testes', tipo: 'projeto', comp: 'Integrar todas as camadas e testar o sistema', hab: 'Verificar funcionalidades, corrigir bugs e testar', aval: 'Checkpoint 2 — sistema integrado', rec: 'Laboratório, VS Code, checklist de testes', quadro: ['PROJETO FINAL — CHECKPOINT 2','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','METAS SEM. 36:','→ Todas as funções implementadas','→ Sem erros críticos (PHP/SQL)','→ Sessão e autenticação OK','→ Interface responsiva',' ','TESTES: Funcional|Usabilidade|Segurança'], guia: null, tempos: [] },
  { sem: 37, tri: 3, tema: 'Projeto Final — ajustes finais, documentação e deploy', tipo: 'projeto', comp: 'Finalizar, documentar e publicar aplicação web', hab: 'Corrigir bugs finais, completar docs e publicar', aval: 'Sistema publicado + documentação entregue', rec: 'Laboratório, servidor para deploy, VS Code', quadro: ['PROJETO FINAL — ENTREGA','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','ENTREGÁVEIS:','  1. Sistema publicado (URL)','  2. Código no GitHub','  3. Documentação técnica (PDF)','  4. Manual do usuário',' ','RUBRICA: Func.|Design|Código|Docs'], guia: null, tempos: [] },
  { sem: 38, tri: 3, tema: 'AQL — banca avaliadora do Projeto Final', tipo: 'aval', comp: 'AQL final: produção 40% + oralidade 30% + participação 30%', hab: 'Apresentar e defender projeto com demonstração ao vivo', aval: 'AQL final — nota mínima 6,0 — IN SUPEN 4/2024', rec: 'Projetor, ficha de avaliação da banca', quadro: ['AQL FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','BANCA AVALIADORA','  Produção Textual (40%):','    → Documentação técnica','  Oralidade (30%):','    → Demo ao vivo + perguntas','  Participação (30%):','    → Engajamento no trimestre',' ','DURAÇÃO: 10 min por grupo'], guia: null, tempos: [] },
  { sem: 39, tri: 3, tema: 'AQT — Avaliação Específica Final: prova integrada', tipo: 'aval', comp: 'AQT final: avaliação quantitativa do 3º trimestre', hab: 'Demonstrar domínio de frameworks, segurança e deploy', aval: '50% objetiva + 50% discursiva — escala 0 a 10', rec: 'Prova impressa, sala de aula', quadro: ['AQT FINAL — 3º TRIMESTRE','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONTEÚDO:','  Frameworks web (rotas, ORM)','  Segurança (SQL Injection, XSS)','  Deploy e publicação','  Boas práticas',' ','5 objetivas (50%) + 2 discursivas (50%)'], guia: null, tempos: [] },
  { sem: 40, tri: 3, tema: 'Conselho de Classe, revisão anual e encerramento', tipo: 'aval', comp: 'Avaliação global e encerramento do ano letivo', hab: 'Refletir sobre o percurso e identificar aprendizagens', aval: 'Conselho de Classe — art. 17 Regimento SEDUC-PI', rec: 'Ficha do Conselho de Classe, diário de bordo', quadro: ['ENCERRAMENTO — SEM. 40','━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','CONSELHO DE CLASSE:','→ Análise da turma (rendimento)','→ Alunos com nota < 6,0','→ Deliberação: aprovação / PF',' ','PROVA FINAL (PF):','→ Para alunos com MA < 6,0','→ Frequência mínima 75%'], guia: null, tempos: [] }
];
